"""Permutation-symmetric ansatz: decompositions of |M>^m whose set of terms
is invariant under every permutation of the copies.

Motivation (symmetric.py): the unique rank-4 decompositions of |N>^3 and
|H3>^3 are invariant as sets under all of S_3, and the rank-3 decomposition
of |T>^4 under a subgroup of S_4 of order 8. If psi = sum_j c_j s_j has an
S_m-invariant term set with independent terms, applying a permutation g and
using the uniqueness of the coefficients gives c_{g(j)} = c_j lambda_{g,j}
(g s_j = lambda_{g,j} s_{g(j)}), so the coefficients are constant along each
orbit up to the phases of the action, and the decomposition is a combination
of orbit vectors v_O = sum_{g in S_m} g s (the symmetrisation of any member),
each costing |O| terms. v_O vanishes exactly when the stabilizer of s acts on
it with a nontrivial character, so such orbits cannot occur. The question
"is there an S_m-invariant decomposition with at most R terms" is therefore
a rank problem over the orbit vectors with |O| <= R, weighted by cost.

Enumeration without the full dictionary. Stabilizer states are generated by
affine flat (RREF basis W, coset representative x0) and phase form (Q, l). A
permutation of the qutrits maps the flat to another flat; only states on a
flat whose S_m-stabilizer has order at least m!/R can have an orbit of size
at most R, so most flats are skipped without generating their 3^(k(k+3)/2)
states, and on the remaining flats the stabilizer of each state is read off
the phase exponents (g s = w^c s iff the exponents shift by a constant along
the induced permutation of the support).

Search. Over the orbit vectors of cost <= R: single vectors proportional to
psi, pairs (rank_exclusion.rank2_search), triples (rank3_search) and
quadruples (slice_lift.decompositions_with_pivot, rank 4), each filtered by
total cost; combinations of five or six orbits are brute-forced when they
can only involve orbits of cost 1 and 2. Everything is exact up to the
1e-9 residual tolerance of those searches; a hit is written as amplitude
vectors for to_witness.py.

Usage: perm_symmetric.py ORBIT M RMAX [MAX_ORBITS]
"""

from __future__ import annotations

import itertools
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ORBIT_P, target  # noqa: E402

W3 = np.exp(2j * np.pi / 3)


def rref_bases(k, m, p):
    """All k x m matrices over F_p in reduced row echelon form."""
    if k == 0:
        yield np.zeros((0, m), dtype=np.int64)
        return
    for piv in itertools.combinations(range(m), k):
        free = [(r, c) for r in range(k) for c in range(m)
                if c > piv[r] and c not in piv]
        for vals in itertools.product(range(p), repeat=len(free)):
            W = np.zeros((k, m), dtype=np.int64)
            for r in range(k):
                W[r, piv[r]] = 1
            for (r, c), v in zip(free, vals):
                W[r, c] = v
            yield W


def flats(m, p):
    """(W, x0) for every affine flat: x0 ranges over vectors vanishing on the
    pivot columns of W."""
    for k in range(m + 1):
        for W in rref_bases(k, m, p):
            piv = [int(np.flatnonzero(W[r])[0]) for r in range(k)]
            nonpiv = [c for c in range(m) if c not in piv]
            for vals in itertools.product(range(p), repeat=len(nonpiv)):
                x0 = np.zeros(m, dtype=np.int64)
                for c, v in zip(nonpiv, vals):
                    x0[c] = v
                yield k, W, x0


def perm_index_maps(m, p):
    """For each permutation of the qudits, the induced permutation of the
    computational basis indices: new_index[old_index]."""
    dim = p ** m
    idx = np.arange(dim)
    digits = (idx[:, None] // p ** (m - 1 - np.arange(m))[None, :]) % p
    weights = p ** (m - 1 - np.arange(m))
    maps = []
    for perm in itertools.permutations(range(m)):
        moved = digits[:, list(perm)]
        maps.append(moved @ weights)
    return maps


def phase_chunks(Mono, nf, p, flat_perms, chunk=1 << 17):
    """Exponent rows E for all (Q, l) on one flat, in chunks, with the number
    of flat permutations fixing each state up to phase and whether every
    fixing permutation acts with the trivial character."""
    total = p ** nf
    digits_w = p ** np.arange(nf)[::-1] if nf else np.zeros(0, dtype=np.int64)
    for lo in range(0, total, chunk):
        idx = np.arange(lo, min(total, lo + chunk))
        coeffs = (idx[:, None] // digits_w[None, :]) % p if nf else np.zeros((len(idx), 0), dtype=np.int64)
        E = (coeffs @ Mono.T) % p
        stab_count = np.zeros(len(E), dtype=np.int64)
        char_trivial = np.ones(len(E), dtype=bool)
        for sigma in flat_perms:
            diff = (E[:, sigma] - E) % p
            const = (diff == diff[:, :1]).all(axis=1)
            stab_count += const
            char_trivial &= ~(const & (diff[:, 0] != 0))
        yield E, stab_count, char_trivial


def cost_rank_search(D, psi, costs, R, max_orbits=None):
    """Every index set S with sum of costs <= R and psi in span(D[:, S]),
    minimal in the sense that no proper subset spans psi.

    Size s sets are found from their s-2 smallest indices as pivots: modulo
    span(psi, pivots) the two remaining members have parallel images
    (rank_exclusion's organisation), found by sorting; every candidate is
    confirmed in the full space. Pivot tuples are pruned by cost.
    """
    from rank_exclusion import _parallel_groups
    rng = np.random.default_rng(3)
    n = D.shape[1]
    psi = psi / np.linalg.norm(psi)
    costs = np.asarray(costs)
    hits = []
    tested = {}
    # singles
    for j in range(n):
        if abs(abs(np.vdot(D[:, j], psi)) - 1) < 1e-9:
            hits.append(((j,), int(costs[j])))
    tested[1] = n

    def confirm(cols):
        A = D[:, list(cols)]
        if np.linalg.matrix_rank(A, tol=1e-8) < len(cols):
            return False
        x, *_ = np.linalg.lstsq(A, psi, rcond=None)
        return np.linalg.norm(A @ x - psi) < 1e-9

    def pair_search(pivots, budget):
        """Pairs (a, b) with a, b > max(pivots), cost(a) + cost(b) <= budget,
        psi in span(pivots, a, b)."""
        last = max(pivots) if pivots else -1
        cand = np.flatnonzero((np.arange(n) > last) & (costs <= budget - 1))
        if len(cand) < 2:
            return []
        B, _ = np.linalg.qr(np.column_stack([psi] + [D[:, i] for i in pivots]))
        q = D[:, cand] - B @ (B.conj().T @ D[:, cand])
        nq = np.linalg.norm(q, axis=0)
        keep = nq > 1e-7
        cand, q = cand[keep], q[:, keep] / nq[keep]
        if len(cand) < 2:
            return []
        groups, _ = _parallel_groups(q, rng)
        out = []
        for g in groups:
            gi = cand[g]
            for a in range(len(gi)):
                for b in range(a + 1, len(gi)):
                    if costs[gi[a]] + costs[gi[b]] <= budget:
                        cols = tuple(pivots) + (int(gi[a]), int(gi[b]))
                        if confirm(cols):
                            out.append(cols)
        return out

    # span pruning: psi must lie in the span of every vector of cost <= c for
    # a set whose members all have cost <= c
    in_span = {}
    for c in sorted(set(int(x) for x in costs)):
        A = D[:, costs <= c]
        x, *_ = np.linalg.lstsq(A, psi, rcond=None)
        in_span[c] = bool(np.linalg.norm(A @ x - psi) < 1e-9)
    print(f"  psi in the span of all orbit vectors of cost <= c: {in_span}", flush=True)
    cost_levels = sorted(in_span)

    def level(c):
        return min(x for x in cost_levels if x >= c) if any(x >= c for x in cost_levels) else cost_levels[-1]

    for size in range(2, (R if max_orbits is None else min(R, max_orbits)) + 1):
        count = 0
        # pivot tuples: s-2 indices in increasing order with total cost <= R - 2
        def rec(pivots, start, spent):
            nonlocal count
            if len(pivots) == size - 2:
                cmax = max([int(costs[i]) for i in pivots] + [R - spent - 1])
                if not in_span[level(cmax)]:
                    return
                count += 1
                for cols in pair_search(pivots, R - spent):
                    hits.append((cols, int(costs[list(cols)].sum())))
                return
            remaining = size - 2 - len(pivots)
            for i in range(start, n):
                c = spent + int(costs[i])
                if c + remaining - 1 + 2 > R:        # each remaining member costs >= 1
                    continue
                rec(pivots + [i], i + 1, c)
        rec([], 0, 0)
        tested[size] = count
    # dedupe
    uniq = {}
    for cols, c in hits:
        uniq[tuple(sorted(cols))] = c
    return [(k, v) for k, v in uniq.items()], tested


def main(argv):
    orbit, m, R = argv[1], int(argv[2]), int(argv[3])
    max_orbits = int(argv[4]) if len(argv) > 4 else None
    p = ORBIT_P[orbit]
    assert p == 3, "qutrit orbits only"
    psi = target(orbit, m)
    dim = p ** m
    perms = perm_index_maps(m, p)
    G = len(perms)
    min_stab = -(-G // R)          # orbit <= R  <=>  |Stab| >= G/R
    weights = p ** (m - 1 - np.arange(m))
    t0 = time.time()
    orbit_vecs, costs, reps = [], [], []
    seen = set()
    n_flats = n_kept_flats = n_states = 0
    for k, W, x0 in flats(m, p):
        n_flats += 1
        ys = np.array(list(itertools.product(range(p), repeat=k)), dtype=np.int64).reshape(p ** k, k)
        pts = (x0[None, :] + ys @ W) % p                    # (3^k, m)
        supp = pts @ weights                                  # indices
        supp_set = set(int(s) for s in supp)
        pos = {int(s): i for i, s in enumerate(supp)}
        # permutations preserving the flat, with the induced permutation of the support
        flat_perms = []
        for g in perms:
            img = g[supp]
            if all(int(s) in supp_set for s in img):
                flat_perms.append(np.array([pos[int(s)] for s in img]))
        if len(flat_perms) < min_stab:
            continue
        n_kept_flats += 1
        # phase exponents for all (Q, l): quadratic monomials y_i y_j (i <= j) and y_i
        monos = [ys[:, i] * ys[:, j] for i in range(k) for j in range(i, k)] + [ys[:, i] for i in range(k)]
        Mono = np.array(monos, dtype=np.int64).T if monos else np.zeros((len(ys), 0), dtype=np.int64)
        nf = Mono.shape[1]
        n_states += p ** nf
        for E, stab_count, char_trivial in phase_chunks(Mono, nf, p, flat_perms):
          keep = (stab_count >= min_stab) & char_trivial
          for row in np.flatnonzero(keep):
              v = np.zeros(dim, dtype=complex)
              v[supp] = W3 ** E[row]
              v /= np.linalg.norm(v)
              sym = np.zeros(dim, dtype=complex)
              for g in perms:
                  w = np.zeros(dim, dtype=complex)
                  w[g] = v
                  sym += w
              if np.linalg.norm(sym) < 1e-9:
                  continue
              sym /= np.linalg.norm(sym)
              j = np.flatnonzero(np.abs(sym) > 1e-9)[0]
              keyv = (np.round(sym * (abs(sym[j]) / sym[j]), 6) + 0.0).tobytes()
              if keyv in seen:
                  continue
              seen.add(keyv)
              orbit_vecs.append(sym)
              costs.append(G // int(stab_count[row]))
              reps.append(v)
    costs = np.array(costs)
    print(f"{orbit} m={m}: {n_flats} flats, {n_kept_flats} with a permutation stabilizer of order >= {min_stab}, "
          f"{n_states} states on them, {len(orbit_vecs)} S_{m}-orbits of size <= {R} with trivial character; "
          f"sizes: {dict(zip(*np.unique(costs, return_counts=True)))} [{time.time() - t0:.0f}s]", flush=True)
    if not orbit_vecs:
        return 0
    D = np.column_stack(orbit_vecs)
    hits, tested = cost_rank_search(D, psi, costs, R, max_orbits)
    for size in sorted(tested):
        print(f"  {size}-orbit unions within cost {R}: {tested[size]} pivot sets scanned", flush=True)
    if max_orbits is not None and max_orbits < R:
        print(f"  unions of more than {max_orbits} orbits were not scanned", flush=True)
    print(f"{len(hits)} S_{m}-invariant decompositions with at most {R} terms")
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "results")
    os.makedirs(out, exist_ok=True)
    for h, (cols, c) in enumerate(hits):
        terms = []
        for j in cols:
            v = reps[j]
            for g in perms:
                w = np.zeros(dim, dtype=complex)
                w[g] = v
                jj = np.flatnonzero(np.abs(w) > 1e-9)[0]
                kw = (np.round(w * (abs(w[jj]) / w[jj]), 6) + 0.0).tobytes()
                if kw not in {t[1] for t in terms}:
                    terms.append((w, kw))
        vecs = [t[0] for t in terms]
        A = np.column_stack(vecs)
        x, *_ = np.linalg.lstsq(A, psi, rcond=None)
        res = np.linalg.norm(A @ x - psi)
        path = os.path.join(out, f"perm_{orbit}_m{m}_rank{len(vecs)}_hit{h}.json")
        import json
        with open(path, "w") as fh:
            json.dump([[[float(z.real), float(z.imag)] for z in t] for t in vecs], fh)
        print(f"  hit {h}: orbits {cols}, {len(vecs)} terms, residual {res:.1e}, written {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
