"""Pauli-group eigensector decompositions of |M>^m for every prime on the board.

Generalizes sectors.py (qutrits, one Pauli string) to p in {2, 3, 5} and to
groups generated by k commuting Pauli strings. For an abelian group G of
Pauli strings with p^k elements and full support on the m copies (every copy
carries a nonidentity element of G), |M>^m = sum_s Pi_s |M>^m over the p^k
joint eigensectors s, so chi(|M>^m) <= sum_s chi(Pi_s |M>^m). A sector lives
in the stabilizer code {P_i = w^{s_i}}, and a Clifford C with C P_i C^-1 = Z_i
turns it into |s> (x) u_s with u_s an (m-k)-qudit state whose stabilizer rank
is the sector's rank (any decomposition of the sector projects into the code
term by term). The rank of u_s is decided exactly in the (m-k)-qudit
dictionary when that dictionary fits (five qubits, three qutrits, two
ququints): 1 if u_s is a stabilizer state, 2 by rank2_search, 3 by
rank3_search with --rank3, else "> 3". Without a dictionary the script
reports 0, 1, or ">= 2" and, with --anneal R, runs a short annealing search
for a rank-R decomposition of u_s.

The 2026-09-24 identity chi(|T5>^2) = 5 is the case p = 5, m = 2, G = <Z Z>:
every sector is a stabilizer state. This script finds it in under a second
(`sectors_p.py T5 2`), which is the control.

Enumeration. For k = 1 the strings are taken up to the local Clifford
stabilizer of |M> on each copy and the copy permutations, as in sectors.py.
For k = 2 the pairs (P1, P2) with P1 a k = 1 representative and P2 any
string are screened first by the sector weights, which are cheap: the weight
of sector s is the Fourier transform over G of the expectation values
<psi|g|psi> = prod_i <M|g_i|M>. Only pairs whose number of nonvanishing
sectors is below the cell's current upper bound go to the rank analysis,
since every nonvanishing sector costs at least one term. Pairs are deduped
by the group they generate.

Usage:
    sectors_p.py ORBIT M [--k 1|2] [--rank3] [--anneal R] [--bound B]
                 [--only "X^aZ^c X^aZ^c ..."] [--control]
"""

from __future__ import annotations

import argparse
import itertools
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import alpha, target  # noqa: E402
from rank_exclusion import clifford_group, dictionary, rank2_search, rank3_search  # noqa: E402
from stabrank_verify import ORBIT_P  # noqa: E402
from to_witness import NotStabilizer, term_from_vector  # noqa: E402

DICT_CAP = {2: 5, 3: 3, 5: 2}     # largest n with an in-memory dictionary
_DICTS = {}


def dict_for(p, n):
    """The (p, n) dictionary, cached in memory and, when SECTORS_DICT_CACHE
    names a directory, on disk (the five-qubit dictionary takes 240 s to
    enumerate and 1.2 GB)."""
    if n < 1 or n > DICT_CAP.get(p, 0):
        return None
    if (p, n) not in _DICTS:
        t0 = time.time()
        cache = os.environ.get("SECTORS_DICT_CACHE")
        path = os.path.join(cache, f"dict_p{p}_n{n}.npy") if cache else None
        if path and os.path.exists(path):
            _DICTS[(p, n)] = np.load(path)
        else:
            _DICTS[(p, n)] = dictionary(p, n)
            if path:
                np.save(path, _DICTS[(p, n)])
        print(f"  [dictionary p={p} n={n}: {_DICTS[(p, n)].shape[1]} states, {time.time() - t0:.0f}s]", flush=True)
    return _DICTS[(p, n)]


# ---------------------------------------------------------------- Paulis ---

def omega(p):
    return np.exp(2j * np.pi / p)


def single_pauli(p, a, c):
    """X^a Z^c as a p x p matrix, X|x> = |x+1>, Z|x> = w^x |x>."""
    w = omega(p)
    X = np.roll(np.eye(p), a, axis=0)
    Z = np.diag(w ** (c * np.arange(p)))
    return X @ Z


def pauli_labels(p):
    return [(a, c) for a in range(p) for c in range(p) if (a, c) != (0, 0)]


def label_str(string):
    return " ".join(f"X^{a}Z^{c}" for a, c in string)


def parse_label(s):
    out = []
    for tok in s.split():
        a, c = tok.replace("X^", "").split("Z^")
        out.append((int(a), int(c)))
    return out


def apply_string(psi, p, m, string, power=1):
    """(x)_i (X^{a_i} Z^{c_i})^power applied to psi, as a vector op."""
    v = psi.reshape((p,) * m)
    w = omega(p)
    for i, (a, c) in enumerate(string):
        for _ in range(power):
            if c:
                shape = [1] * m
                shape[i] = p
                v = v * (w ** (c * np.arange(p))).reshape(shape)
            if a:
                v = np.roll(v, a, axis=i)
    return v.reshape(-1)


def string_scalar(p, string):
    """lambda with P^p = lambda I for P = (x) X^a Z^c."""
    lam = 1.0 + 0j
    for a, c in string:
        q = single_pauli(p, a, c)
        qp = np.linalg.matrix_power(q, p)
        lam *= qp[0, 0]
    return lam


def sector_vectors(psi, p, m, strings):
    """Joint eigensector projections of psi for the commuting strings, as a
    dict s -> vector (s a tuple of eigenvalue exponents)."""
    w = omega(p)
    parts = {(): psi}
    for P in strings:
        lam = string_scalar(p, P)
        root = lam ** (1.0 / p)
        nxt = {}
        for s, v in parts.items():
            powers = [v]
            cur = v
            for _ in range(p - 1):
                cur = apply_string(cur, p, m, P) / root
                powers.append(cur)
            for e in range(p):
                proj = sum(w ** (-e * j) * powers[j] for j in range(p)) / p
                nxt[s + (e,)] = proj
        parts = nxt
    return parts


def commute(p, P, Q):
    return sum(a1 * c2 - a2 * c1 for (a1, c1), (a2, c2) in zip(P, Q)) % p == 0


def independent(p, strings):
    """The strings generate a group of order p^k (no nontrivial relation mod phase)."""
    M = np.array([[x for ac in P for x in ac] for P in strings], dtype=np.int64) % p
    return rank_mod_p(M, p) == len(strings)


def rank_mod_p(M, p):
    M = M.copy() % p
    r = 0
    rows, cols = M.shape
    for c in range(cols):
        piv = next((i for i in range(r, rows) if M[i, c] % p), None)
        if piv is None:
            continue
        M[[r, piv]] = M[[piv, r]]
        M[r] = (M[r] * pow(int(M[r, c]), -1, p)) % p
        for i in range(rows):
            if i != r and M[i, c]:
                M[i] = (M[i] - M[i, c] * M[r]) % p
        r += 1
    return r


# ---------------------------------------------------- Clifford reduction ---

class Reducer:
    """A Clifford, as a gate list, mapping the generators to Z_0, ..., Z_{k-1}.

    Symplectic rules (a, c per site): F_i: (a, c) -> (-c, a); S_i^k: (a, c) ->
    (a, c + k a); M_{u, i}: (a, c) -> (u a, u^-1 c); SUM_{i -> j}: a_j += a_i,
    c_i -= c_j; SWAP. Each gate is applied to vectors as an index or phase
    operation; --control checks the rules against dense matrices.
    """

    def __init__(self, p, m):
        self.p, self.m, self.gates = p, m, []

    def build(self, strings):
        p, m = self.p, self.m
        cur = [[list(ac) for ac in P] for P in strings]

        def F(i):
            self.gates.append(("F", i))
            for P in cur:
                a, c = P[i]
                P[i] = [(-c) % p, a % p]

        def S(i, k):
            k %= p
            if k:
                self.gates.append(("S", i, k))
                for P in cur:
                    a, c = P[i]
                    P[i] = [a, (c + k * a) % p]

        def Mul(i, u):
            u %= p
            if u != 1:
                self.gates.append(("M", i, u))
                ui = pow(u, -1, p)
                for P in cur:
                    a, c = P[i]
                    P[i] = [(u * a) % p, (ui * c) % p]

        def SUM(i, j, times=1):
            times %= p
            for _ in range(times):
                self.gates.append(("SUM", i, j))
                for P in cur:
                    P[j][0] = (P[j][0] + P[i][0]) % p
                    P[i][1] = (P[i][1] - P[j][1]) % p

        def SWAP(i, j):
            if i != j:
                self.gates.append(("SWAP", i, j))
                for P in cur:
                    P[i], P[j] = P[j], P[i]

        for t in range(len(strings)):
            P = cur[t]
            for i in range(t):
                assert P[i][0] == 0, "generator does not commute with the reduced Z's"
            active = [i for i in range(t, m) if P[i] != [0, 0]]
            assert active, "dependent generator"
            for i in active:
                if P[i][0] == 0:
                    F(i)
                a, c = P[i]
                S(i, (-c * pow(a, -1, p)) % p)
                Mul(i, pow(P[i][0], -1, p))
            i0 = active[0]
            for i in active[1:]:
                SUM(i0, i, p - 1)           # SUM^{-1}: X_i0 X_i -> X_i0
            F(i0)                            # X_i0 -> Z_i0
            for i in range(t):
                SUM(i, i0, P[i][1])          # remove Z_i^{c} from Z_i^c Z_i0
            SWAP(t, i0)
            assert all(cur[t][i] == [0, 0] for i in range(m) if i != t) and cur[t][t] == [0, 1], cur[t]
        return self

    def apply(self, psi):
        p, m = self.p, self.m
        v = psi.reshape((p,) * m)
        w = omega(p)
        Fm = np.array([[w ** (x * y) for x in range(p)] for y in range(p)]) / np.sqrt(p)
        for g in self.gates:
            if g[0] == "F":
                i = g[1]
                v = np.moveaxis(np.tensordot(Fm, v, axes=([1], [i])), 0, i)
            elif g[0] == "S":
                _, i, k = g
                if p == 2:
                    ph = np.array([1, 1j]) ** k
                else:
                    ph = w ** ((k * np.arange(p) * (np.arange(p) - 1) // 2) % p)
                shape = [1] * m
                shape[i] = p
                v = v * ph.reshape(shape)
            elif g[0] == "M":
                _, i, u = g
                ui = pow(u, -1, p)
                idx = (ui * np.arange(p)) % p          # new(y) = old(u^-1 y)
                v = np.take(v, idx, axis=i)
            elif g[0] == "SUM":
                _, i, j = g
                out = np.empty_like(v)
                for xi in range(p):
                    sl = [slice(None)] * m
                    sl[i] = xi
                    sl = tuple(sl)
                    out[sl] = np.roll(v[sl], xi, axis=j if j < i else j - 1)
                v = out
            elif g[0] == "SWAP":
                v = np.swapaxes(v, g[1], g[2])
        return v.reshape(-1)

    def dense(self):
        """The Clifford as a dense unitary (controls only)."""
        p, m = self.p, self.m
        dim = p ** m
        U = np.eye(dim, dtype=complex)
        for col in range(dim):
            U[:, col] = self.apply(np.eye(dim, dtype=complex)[:, col])
        return U


def reduce_sectors(psi, p, m, strings):
    """[(s, weight, u_s or None)] with u_s the normalized (m-k)-qudit state."""
    k = len(strings)
    secs = sector_vectors(psi, p, m, strings)
    red = Reducer(p, m).build(strings)
    out = []
    for s, v in sorted(secs.items()):
        nrm = np.linalg.norm(v)
        if nrm < 1e-10:
            out.append((s, 0.0, None))
            continue
        wv = red.apply(v).reshape(p ** k, -1)
        blocks = np.linalg.norm(wv, axis=1)
        b = int(np.argmax(blocks))
        if not np.allclose(np.delete(blocks, b), 0, atol=1e-8):
            raise AssertionError("the Clifford reduction did not isolate one block")
        out.append((s, float(nrm ** 2), wv[b] / blocks[b]))
    return out


# ----------------------------------------------------------- rank tests ---

def is_stab(u, p, n):
    try:
        term_from_vector(u, p, n)
        return True
    except (NotStabilizer, ValueError, IndexError):
        return False


def sector_rank(u, p, n, rank3=False, D=None):
    """0, 1, 2, 3, or the strings '>3' (dictionary, rank3 failed) / '>=3'
    (dictionary, rank3 not run) / '>=2' (no dictionary)."""
    if u is None:
        return 0
    if n == 0:
        return 1
    if is_stab(u, p, n):
        return 1
    if D is None:
        return ">=2"
    r2, _ = rank2_search(u, D)
    if r2 == "RANK1":
        return 1
    if r2:
        return 2
    if not rank3:
        return ">=3"
    r = rank3_search(u, D, workers=1)
    return 3 if r["found"] else ">3"


def rank_value(r):
    return {">=2": 2, ">=3": 3, ">3": 4}.get(r, r)


ANNEAL_CFG = {"seeds": 1, "chains": 4, "iters": 2000, "cooling": 0.99}


def anneal(u, p, n, rank):
    """Best of ANNEAL_CFG['seeds'] annealing runs at fixed rank on the sector
    state u (n qudits); returns (residual, seconds, term vectors)."""
    from stabrank import generate_random_stabilizer_state
    from stabrank.stabrank_core import run_sa_pauli_expansion
    t0 = time.time()
    best = None
    for seed in range(1, ANNEAL_CFG["seeds"] + 1):
        np.random.seed(seed)
        basis = [generate_random_stabilizer_state(n, p=p) for _ in range(rank)]
        _, funcs, _, err, _, _ = run_sa_pauli_expansion(
            target=u, n_orig=n, p_prime=p, k_subset_size=rank, initial_basis=basis,
            initial_temperature=1.0, cooling_rate=ANNEAL_CFG["cooling"],
            num_iterations_at_temp=ANNEAL_CFG["iters"],
            min_temperature=1 / 4000, atol=1e-7, two_func_perturb_prob=0.3,
            random_replace_prob=0.05, use_real_qubit_moves=False, clifford_ratio=0.5,
            early_exit_threshold=1e-9, seed=seed, num_chains=ANNEAL_CFG["chains"])
        if best is None or err < best[0]:
            best = (float(err), [np.asarray(f, dtype=complex) for f in funcs])
        if err < 1e-9:
            break
    return best[0], time.time() - t0, best[1]


# ------------------------------------------------------------ enumeration --

def local_orbits(orbit, p):
    """Orbits of the nonidentity single-qudit Paulis under the local Clifford
    stabilizer of |M>, as (reps, order, class_of)."""
    a1 = alpha(orbit)
    G = clifford_group(p)
    stab = [U for U in G if abs(abs(np.vdot(a1, U @ a1)) - 1) < 1e-9]
    labels = pauli_labels(p)

    def key(Pm):
        v = Pm.ravel()
        v = v / v[np.flatnonzero(np.abs(v) > 1e-9)[0]]
        return (np.round(v, 6) + 0.0).tobytes()

    index = {key(single_pauli(p, a, c)): (a, c) for a, c in labels}
    parent = {pc: pc for pc in labels}

    def find(x):
        while parent[x] != x:
            x = parent[x]
        return x

    perms = []
    for U in stab:
        perm = {(0, 0): (0, 0)}
        for a, c in labels:
            img = index[key(U @ single_pauli(p, a, c) @ U.conj().T)]
            perm[(a, c)] = img
            ra, rb = find((a, c)), find(img)
            if ra != rb:
                parent[ra] = rb
        perms.append(perm)
    reps = sorted({find(pc) for pc in labels})
    return reps, len(stab), {pc: find(pc) for pc in labels}, perms


def gl2(p):
    return [(a, b, c, d) for a in range(p) for b in range(p) for c in range(p) for d in range(p)
            if (a * d - b * c) % p]


def canonical_pair(p, P1, P2, perms, G2=None):
    """Canonical form of the group <P1, P2> under the local stabilizer on each
    copy, the copy permutations, and the change of generators (GL_2(F_p))."""
    G2 = G2 or gl2(p)
    best = None
    for a, b, c, d in G2:
        sites = []
        for (a1, c1), (a2, c2) in zip(P1, P2):
            q1 = ((a * a1 + b * a2) % p, (a * c1 + b * c2) % p)
            q2 = ((c * a1 + d * a2) % p, (c * c1 + d * c2) % p)
            sites.append(min((perm[q1], perm[q2]) for perm in perms))
        key = tuple(sorted(sites))
        if best is None or key < best:
            best = key
    return best


def k1_classes(orbit, p, m):
    reps, order, _, _ = local_orbits(orbit, p)
    return [list(c) for c in itertools.combinations_with_replacement(reps, m)], order, reps


def expectation_table(orbit, p):
    """e[(a, c)][j] = <M| (X^a Z^c)^j |M> and the scalar of (X^a Z^c)^p."""
    a1 = alpha(orbit)
    e, lam = {}, {}
    for a, c in pauli_labels(p):
        q = single_pauli(p, a, c)
        pw = np.eye(p, dtype=complex)
        vals = []
        for _ in range(p):
            vals.append(np.vdot(a1, pw @ a1))
            pw = pw @ q
        e[(a, c)] = np.array(vals)
        lam[(a, c)] = pw[0, 0]
    return e, lam


_SITE_TABLES = {}


def site_tables(orbit, p):
    """t[q1, q2, j, l] = <M| q1^j q2^l |M> over the nonidentity Paulis, and the
    scalars lam[q] with q^p = lam I."""
    if (orbit, p) in _SITE_TABLES:
        return _SITE_TABLES[(orbit, p)]
    a1 = alpha(orbit)
    labels = pauli_labels(p)
    L = len(labels)
    mats = {q: single_pauli(p, *q) for q in labels}
    powers = {q: [np.linalg.matrix_power(mats[q], j) for j in range(p)] for q in labels}
    lam = np.array([np.linalg.matrix_power(mats[q], p)[0, 0] for q in labels])
    t = np.zeros((L, L, p, p), dtype=complex)
    for i1, q1 in enumerate(labels):
        for i2, q2 in enumerate(labels):
            for j in range(p):
                for l in range(p):
                    t[i1, i2, j, l] = np.vdot(a1, powers[q1][j] @ powers[q2][l] @ a1)
    _SITE_TABLES[(orbit, p)] = (t, lam)
    return t, lam


def pair_weights_batch(orbit, p, m, P1, strings2=None, S2=None):
    """Number of nonvanishing joint sectors for (P1, P2) over a batch of P2,
    given as label tuples (strings2) or as label-index arrays S2 (B, m).

    <psi| P1^j P2^l |psi> = prod_i <M| q1_i^j q2_i^l |M> up to the rescaling
    of P1 and P2 to order p; the weights are its Fourier transform."""
    w = omega(p)
    labels = pauli_labels(p)
    idx = {q: i for i, q in enumerate(labels)}
    t, lam = site_tables(orbit, p)
    if S2 is None:
        S2 = np.array([[idx[q] for q in P2] for P2 in strings2])
    i1s = np.array([idx[tuple(q)] for q in P1])
    lam1 = np.prod(lam[i1s]) ** (1.0 / p)
    lam2 = np.prod(lam[S2], axis=1) ** (1.0 / p)                       # (B,)
    E = np.ones((S2.shape[0], p, p), dtype=complex)
    for i in range(m):
        E *= t[i1s[i], S2[:, i]]                                        # (B, p, p)
    j = np.arange(p)
    E *= (lam1 ** (-j))[None, :, None] * (lam2[:, None, None] ** (-j)[None, None, :])
    Fm = np.array([[w ** (-s * jj) for jj in range(p)] for s in range(p)]) / p
    W = np.einsum("sj,bjl,tl->bst", Fm, E, Fm)                         # weights (B, p, p)
    W = np.abs(W)
    return (W > 1e-9).sum(axis=(1, 2)), W


def partners(p, m, P1, S_all, A):
    """Indices into S_all of the strings commuting with P1 and independent of it."""
    P1a = np.array(P1)                                                  # (m, 2)
    a2, c2 = A[S_all][:, :, 0], A[S_all][:, :, 1]                       # (N, m)
    symp = (P1a[:, 0][None, :] * c2 - a2 * P1a[:, 1][None, :]).sum(axis=1) % p
    ok = symp == 0
    for jmul in range(1, p):
        mult = (jmul * P1a) % p
        ok &= ~np.all((a2 == mult[:, 0][None, :]) & (c2 == mult[:, 1][None, :]), axis=1)
    return np.flatnonzero(ok)


def group_key(p, strings):
    """The set of group elements mod phase, as a frozenset of tuples."""
    k = len(strings)
    elems = set()
    for coeffs in itertools.product(range(p), repeat=k):
        v = [0] * (2 * len(strings[0]))
        for cf, P in zip(coeffs, strings):
            for i, (a, c) in enumerate(P):
                v[2 * i] = (v[2 * i] + cf * a) % p
                v[2 * i + 1] = (v[2 * i + 1] + cf * c) % p
        elems.add(tuple(v))
    return frozenset(elems)


# ------------------------------------------------------------------ main ---

ANNEAL_HITS = []


def analyse(orbit, p, m, strings, rank3, D, anneal_rank=None, verbose=True, anneal_sectors=None):
    psi = target(orbit, m)
    n = m - len(strings)
    secs = reduce_sectors(psi, p, m, strings)
    ranks, weights = [], []
    annealed = 0
    for s, wgt, u in secs:
        r = sector_rank(u, p, n, rank3=rank3, D=D)
        if anneal_rank and r in (">=2", ">=3") and u is not None and (anneal_sectors is None or annealed < anneal_sectors):
            annealed += 1
            err, secs_, vecs = anneal(u, p, n, anneal_rank)
            if err > 1e-9:
                r = f"anneal r={anneal_rank} residual {err:.4f} ({secs_:.0f}s)"
            else:
                r = f"<={anneal_rank} (annealed, {secs_:.0f}s)"
                ANNEAL_HITS.append((strings, s, u, vecs))
        ranks.append(r)
        weights.append(round(wgt, 4))

    def val(r):
        if isinstance(r, str) and r.startswith("<="):
            return anneal_rank
        if isinstance(r, str) and r.startswith("anneal"):
            return 2
        return rank_value(r)

    total = sum(val(r) for r in ranks)
    if verbose:
        print(f"  {' | '.join(label_str(P) for P in strings)}: weights {weights}, ranks {ranks}, "
              f"total >= {total}", flush=True)
    return ranks, weights, total


def save_hits(path):
    if not path or not ANNEAL_HITS:
        return
    np.savez(path, **{f"hit{i}_sector": np.array([str(strings), str(s)]) for i, (strings, s, u, vecs) in enumerate(ANNEAL_HITS)},
             **{f"hit{i}_target": u for i, (strings, s, u, vecs) in enumerate(ANNEAL_HITS)},
             **{f"hit{i}_terms": np.array(vecs) for i, (strings, s, u, vecs) in enumerate(ANNEAL_HITS)})
    print(f"saved {len(ANNEAL_HITS)} annealed sector decompositions to {path}")


def control(argv_orbit=None):
    """Dense checks of the symplectic rules, and the known sector results."""
    rng = np.random.default_rng(3)
    for p, m in [(2, 3), (3, 3), (5, 2), (3, 4)]:
        for _ in range(6):
            k = 1 if p == 5 or m < 3 else 2
            while True:
                strings = [[tuple(int(x) for x in rng.integers(0, p, 2)) for _ in range(m)] for _ in range(k)]
                if all(any(ac != (0, 0) for ac in P) for P in strings) and \
                   all(commute(p, strings[i], strings[j]) for i in range(k) for j in range(i + 1, k)) and \
                   independent(p, strings):
                    break
            red = Reducer(p, m).build(strings)
            U = red.dense()
            assert np.allclose(U.conj().T @ U, np.eye(p ** m), atol=1e-9), "not unitary"
            for t, P in enumerate(strings):
                Pd = np.array([[1.0 + 0j]])
                for a, c in P:
                    Pd = np.kron(Pd, single_pauli(p, a, c))
                Zt = np.array([[1.0 + 0j]])
                for i in range(m):
                    Zt = np.kron(Zt, single_pauli(p, 0, 1) if i == t else np.eye(p))
                Q = U @ Pd @ U.conj().T
                ratio = Q[np.abs(Zt) > 0.5] / Zt[np.abs(Zt) > 0.5]
                assert np.allclose(ratio, ratio[0], atol=1e-8) and np.allclose(np.abs(Q - ratio[0] * Zt), 0, atol=1e-8), \
                    f"reduction failed at p={p} m={m} {strings}"
    print("Clifford reduction: dense checks pass (p = 2, 3, 5)")
    # T5 m=2, Z Z: all five sectors stabilizer states
    r, _, tot = analyse("T5", 5, 2, [[(0, 1), (0, 1)]], False, dict_for(5, 1))
    assert r == [1] * 5 and tot == 5, r
    print("T5 m=2 Z Z: five stabilizer sectors, total 5 (chi(T5^2) = 5)")
    # T3 m=3, Z Z Z: three sectors of rank 3 (exhaustive fact behind T3-m5-upper-18)
    r, _, tot = analyse("T3", 3, 3, [[(0, 1)] * 3], True, dict_for(3, 2))
    assert r == [3, 3, 3], r
    print("T3 m=3 Z Z Z: sector ranks 3, 3, 3")
    # N m=3, X^2 X^2 X^2 has one rank-2 sector (sectors.py, 2026-09-20)
    r, _, tot = analyse("N", 3, 3, [[(2, 0)] * 3], True, dict_for(3, 2))
    assert sorted(rank_value(x) for x in r)[0] == 2, r
    print("N m=3 X^2 X^2 X^2: one rank-2 sector")
    # weight formula against explicit projections
    for orbit, p, m in [("T5", 5, 2), ("N", 3, 3), ("qubit_H", 2, 4), ("S", 3, 4)]:
        labels = pauli_labels(p)
        psi = target(orbit, m)
        for _ in range(5):
            while True:
                P1 = [labels[int(i)] for i in rng.integers(0, len(labels), m)]
                P2 = [labels[int(i)] for i in rng.integers(0, len(labels), m)]
                if commute(p, P1, P2) and independent(p, [P1, P2]):
                    break
            cnt, W = pair_weights_batch(orbit, p, m, P1, [P2])
            secs = sector_vectors(psi, p, m, [P1, P2])
            direct = sorted(np.linalg.norm(v) ** 2 for v in secs.values())
            assert np.allclose(sorted(W[0].ravel()), direct, atol=1e-8), (orbit, P1, P2)
    print("sector weights: Fourier formula matches explicit projections")
    return 0


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("orbit", nargs="?")
    ap.add_argument("m", nargs="?", type=int)
    ap.add_argument("--k", type=int, default=1)
    ap.add_argument("--rank3", action="store_true")
    ap.add_argument("--anneal", type=int, default=None, help="anneal undecided sectors at this rank")
    ap.add_argument("--bound", type=int, default=None,
                    help="current upper bound of the cell; k = 2 pairs with at least this many "
                         "nonvanishing sectors are skipped")
    ap.add_argument("--only", default=None, help="one string (k = 1) or 'P1 | P2' (k = 2) to analyse")
    ap.add_argument("--control", action="store_true")
    ap.add_argument("--max-pairs", type=int, default=100000, help="rank analysis on at most this many pair classes")
    ap.add_argument("--anneal-sectors", type=int, default=None, help="anneal at most this many sectors per group")
    ap.add_argument("--skip", type=int, default=0, help="skip the first N pair classes (resume a killed run)")
    ap.add_argument("--anneal-seeds", type=int, default=1)
    ap.add_argument("--anneal-chains", type=int, default=4)
    ap.add_argument("--anneal-iters", type=int, default=2000)
    ap.add_argument("--anneal-cooling", type=float, default=0.99)
    ap.add_argument("--save-hits", default=None, help="write annealed sector decompositions here (npz)")
    a = ap.parse_args(argv[1:])
    if a.control:
        return control()
    ANNEAL_CFG.update(seeds=a.anneal_seeds, chains=a.anneal_chains, iters=a.anneal_iters,
                      cooling=a.anneal_cooling)
    orbit, m = a.orbit, a.m
    p = ORBIT_P[orbit]
    t0 = time.time()
    if a.only:
        strings = [parse_label(s) for s in a.only.split("|")]
        D = dict_for(p, m - len(strings))
        analyse(orbit, p, m, strings, a.rank3, D, anneal_rank=a.anneal, anneal_sectors=a.anneal_sectors)
        save_hits(a.save_hits)
        return 0
    classes, order, reps = k1_classes(orbit, p, m)
    print(f"{orbit} m={m} p={p}: local stabilizer of order {order}, {len(reps)} orbits of nonidentity "
          f"Paulis {reps}, {len(classes)} single-string classes with full support")
    if a.k == 1:
        D = dict_for(p, m - 1)
        best = None
        for cls in classes:
            ranks, weights, total = analyse(orbit, p, m, [cls], a.rank3, D, anneal_rank=a.anneal,
                                            anneal_sectors=a.anneal_sectors)
            if best is None or total < best[0]:
                best = (total, cls, ranks)
        print(f"smallest sector-rank total {best[0]} at {label_str(best[1])} {best[2]} [{time.time() - t0:.0f}s]")
        save_hits(a.save_hits)
        return 0
    # k = 2: screen every (P1 rep, P2) by nonvanishing-sector count
    labels = pauli_labels(p)
    A = np.array(labels)
    S_all = np.array(list(itertools.product(range(len(labels)), repeat=m)), dtype=np.int64)
    bound = a.bound if a.bound is not None else p ** 2 + 1
    print(f"k=2: {len(classes)} P1 classes x {len(S_all)} P2 strings; keeping pairs with fewer than "
          f"{bound} nonvanishing sectors")
    seen_groups = set()
    kept = []
    hist = {}
    _, _, _, perms = local_orbits(orbit, p)
    G2 = gl2(p)
    for cls in classes:
        P1 = [tuple(x) for x in cls]
        cand = partners(p, m, P1, S_all, A)
        for start in range(0, len(cand), 20000):
            S2 = S_all[cand[start:start + 20000]]
            cnt, W = pair_weights_batch(orbit, p, m, P1, S2=S2)
            vals, counts = np.unique(cnt, return_counts=True)
            for v, c in zip(vals, counts):
                hist[int(v)] = hist.get(int(v), 0) + int(c)
            for row in np.flatnonzero(cnt < bound):
                P2 = [labels[i] for i in S2[row]]
                gk = canonical_pair(p, P1, P2, perms, G2)
                if gk in seen_groups:
                    continue
                seen_groups.add(gk)
                kept.append((int(cnt[row]), P1, P2))
    print(f"nonvanishing-sector histogram over all commuting independent pairs: {dict(sorted(hist.items()))} "
          f"[{time.time() - t0:.0f}s]")
    print(f"{len(kept)} pair classes (up to the local stabilizer, copy permutations, and change of "
          f"generators) with fewer than {bound} nonvanishing sectors")
    kept.sort(key=lambda t: t[0])
    D = dict_for(p, m - 2) if kept else None
    best = None
    for c, P1, P2 in kept[a.skip: a.skip + a.max_pairs]:
        ranks, weights, total = analyse(orbit, p, m, [P1, P2], a.rank3, D, anneal_rank=a.anneal,
                                        anneal_sectors=a.anneal_sectors)
        if best is None or total < best[0]:
            best = (total, P1, P2, ranks)
    if best:
        print(f"smallest sector-rank total {best[0]} at {label_str(best[1])} | {label_str(best[2])} {best[3]} "
              f"[{time.time() - t0:.0f}s]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
