"""Set-stabilizers of known decompositions under the symmetry group of |M>^m.

A symmetric ansatz (a decomposition that is a union of orbits of a subgroup
H of the symmetry group, with coefficients determined orbit by orbit) can
only produce decompositions whose set of terms is H-invariant. This script
measures how symmetric the known minimal decompositions actually are: for
each stored decomposition it computes the orbit of its term set under the
group generated by the local Clifford stabilizer of |M> on each copy, the
copy permutations and (optionally) the antiunitary symmetry, and reports
|G| / |orbit|, the order of the set-stabilizer. A set-stabilizer of order 1
means the decomposition is a union of orbits of no nontrivial subgroup.

Usage: symmetric.py ORBIT M RANK [--bound bounds/X.json]
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ORBIT_P, load_decompositions, target, term_vector  # noqa: E402
from rank_exclusion import dictionary, symmetry_orbit_reps  # noqa: E402


def key(v):
    v = v / v[np.flatnonzero(np.abs(v) > 1e-9)[0]]
    return (np.round(v, 6) + 0.0).tobytes()


def orbit_size(cols, perms):
    start = tuple(sorted(cols))
    seen = {start}
    frontier = [start]
    while frontier:
        nxt = []
        for s in frontier:
            for pm in perms:
                t = tuple(sorted(int(pm[i]) for i in s))
                if t not in seen:
                    seen.add(t)
                    nxt.append(t)
        frontier = nxt
    return len(seen)


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("orbit")
    ap.add_argument("m", type=int)
    ap.add_argument("rank", type=int)
    ap.add_argument("--bound", default=None)
    a = ap.parse_args(argv[1:])
    p = ORBIT_P[a.orbit]
    D = dictionary(p, a.m)
    index = {key(D[:, i]): i for i in range(D.shape[1])}
    if a.bound:
        sub = json.load(open(a.bound))
        if "witness" not in sub:
            print(f"{a.bound}: no witness terms (Lean-only bound)")
            return 0
        decs = [([term_vector(t, p, a.m) for t in sub["witness"]["terms"]], None)]
    else:
        decs, _ = load_decompositions(a.orbit, a.m, a.rank)
    import math
    for anti in (False, True):
        reps, info = symmetry_orbit_reps(a.orbit, a.m, D, antiunitary=anti)
        if anti and not info["antiunitary"]:
            print(f"{a.orbit}: no antiunitary symmetry")
            continue
        orders = []
        for u, _ in decs:
            cols = [index[key(v)] for v in u]
            n = orbit_size(cols, info["perms"])
            orders.append(info["order"] // n)
        label = "unitary + antiunitary" if anti else "unitary"
        print(f"{a.orbit} m={a.m} rank {a.rank}: {label} group of order {info['order']}; "
              f"set-stabilizer orders of the {len(decs)} decompositions: {orders}")
        if not anti and a.m >= 2:
            # the copy permutations alone: generators are the last two perms
            # (the transposition (0 1) and the m-cycle), the local ones first
            nloc = info["local"]
            perm_gens = info["perms"][nloc:nloc + 2]
            loc_gens = info["perms"][:nloc]
            po = [math.factorial(a.m) // orbit_size([index[key(v)] for v in u], perm_gens) for u, _ in decs]
            lo = [nloc // orbit_size([index[key(v)] for v in u], loc_gens) for u, _ in decs]
            print(f"    copy permutations only (S_{a.m}): set-stabilizer orders {po}; "
                  f"local Clifford stabilizer on copy 1 only (order {nloc}): {lo}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
