"""Permutation-symmetric ansatz search for stabilizer-rank decompositions.

Motivation: for a target of the form |psi>^{tensor m}, unconstrained SA at
m >= 5 fails from random starts, and warm-started low-temperature anneals
collapse into a shared local basin. This module shrinks the discrete search
space by constraining the *basis set* (not the coefficients) to be closed
under a cyclic group of copy shifts.

Ansatz. Fix a shift unit g with g | m and the group G = <s_g> generated by
the cyclic qudit shift by g positions. Each search "seed" j carries an orbit
size o_j dividing |G| = m/g and is constrained to be invariant under the
shift by g*o_j positions. The decomposition basis is the union of the seed
orbits {s_g^t sigma_j : t = 0..o_j-1}, so the effective stabilizer rank is
k = sum_j o_j while the discrete search only steers the seeds. Coefficients
stay free and are recovered by least squares, which keeps the ansatz strictly
more expressive than orbit-constant symmetrization; the known qubit T-type
m = 4 identity, whose basis is fixed pointwise by the shift-by-two but whose
coefficients are not orbit-constant, sits inside this family.

Seeds are initialized as periodic tensor powers of random stabilizer states
(period g*o_j), which are stabilizer states with the required invariance by
construction. Mutations apply single-qudit Clifford/Pauli gates replicated at
every period translate (which preserves periodicity exactly), CZ gates
replicated over all translates (CZs commute, so the replicated product is
exactly shift-invariant even across period blocks), or CX gates replicated
within a period block. A periodicity audit runs periodically and on every
accepted best; a violation raises rather than silently corrupting the ansatz.
"""

from __future__ import annotations

import dataclasses
import math

import numpy as np

from .polynomial_utils import generate_random_stabilizer_state

__all__ = [
    "shift_qudits",
    "periodic_seed",
    "orbit_columns",
    "SymmetricSAConfig",
    "run_symmetric_sa",
]


# ---------------------------------------------------------------------------
# Qudit-permutation and gate primitives (dense, numpy-vectorized)
# ---------------------------------------------------------------------------

def shift_qudits(state: np.ndarray, shift: int, n: int, p: int) -> np.ndarray:
    """Cyclically shift qudit positions by `shift`."""
    tensor = state.reshape((p,) * n)
    axes = np.roll(np.arange(n), shift)
    return np.ascontiguousarray(np.transpose(tensor, axes)).reshape(-1)


def _axis_indices(n: int, p: int, q: int) -> np.ndarray:
    """Index of qudit q for every computational-basis element (shape p^n)."""
    idx = np.arange(p ** n)
    return (idx // (p ** (n - 1 - q))) % p


def apply_x(state: np.ndarray, q: int, n: int, p: int, power: int = 1) -> np.ndarray:
    tensor = state.reshape((p,) * n)
    return np.roll(tensor, power, axis=q).reshape(-1)


def apply_z(state: np.ndarray, q: int, n: int, p: int, power: int = 1) -> np.ndarray:
    omega = np.exp(2j * np.pi / p)
    return state * omega ** (power * _axis_indices(n, p, q))


def apply_s(state: np.ndarray, q: int, n: int, p: int) -> np.ndarray:
    x = _axis_indices(n, p, q)
    if p == 2:
        return state * (1j ** x)
    omega = np.exp(2j * np.pi / p)
    # Qudit phase gate: diag(omega^{x(x-1)/2}) (qutrit: diag(1, 1, omega)).
    return state * omega ** (x * (x - 1) // 2)


def apply_f(state: np.ndarray, q: int, n: int, p: int) -> np.ndarray:
    omega = np.exp(2j * np.pi / p)
    fmat = omega ** np.outer(np.arange(p), np.arange(p)) / np.sqrt(p)
    tensor = state.reshape((p,) * n)
    tensor = np.tensordot(fmat, tensor, axes=([1], [q]))
    # tensordot puts the contracted axis first; move it back to position q.
    tensor = np.moveaxis(tensor, 0, q)
    return np.ascontiguousarray(tensor).reshape(-1)


def apply_cz(state: np.ndarray, q1: int, q2: int, n: int, p: int) -> np.ndarray:
    omega = np.exp(2j * np.pi / p)
    return state * omega ** (_axis_indices(n, p, q1) * _axis_indices(n, p, q2))


def apply_cx(state: np.ndarray, control: int, target: int, n: int, p: int) -> np.ndarray:
    tensor = state.reshape((p,) * n)
    out = np.empty_like(tensor)
    for c in range(p):
        sl = [slice(None)] * n
        sl[control] = c
        out[tuple(sl)] = np.roll(tensor[tuple(sl)], c,
                                 axis=target if target < control else target - 1)
    return out.reshape(-1)


# ---------------------------------------------------------------------------
# Seeds and orbits
# ---------------------------------------------------------------------------

def periodic_seed(n: int, p: int, period: int, rng: np.random.Generator) -> np.ndarray:
    """Random stabilizer state on `period` qudits, tensored to n qudits."""
    if n % period != 0:
        raise ValueError("period must divide n")
    block = generate_random_stabilizer_state(
        period, p=p, seed=int(rng.integers(0, 2**31 - 1)))
    state = block
    for _ in range(n // period - 1):
        state = np.kron(state, block)
    return state


def orbit_columns(
    seed: np.ndarray, orbit_size: int, shift_unit: int, n: int, p: int
) -> list[np.ndarray]:
    """The orbit {s_g^t seed : t = 0..orbit_size-1} as LSQ columns."""
    cols = [seed]
    for _ in range(orbit_size - 1):
        cols.append(shift_qudits(cols[-1], shift_unit, n, p))
    return cols


def _is_periodic(state: np.ndarray, period: int, n: int, p: int, tol: float = 1e-9) -> bool:
    shifted = shift_qudits(state, period, n, p)
    # Invariance up to global phase.
    overlap = np.vdot(shifted, state)
    norm_sq = np.vdot(state, state).real
    return abs(abs(overlap) - norm_sq) < tol * max(1.0, norm_sq)


# ---------------------------------------------------------------------------
# SA driver
# ---------------------------------------------------------------------------

@dataclasses.dataclass
class SymmetricSAConfig:
    shift_unit: int                    # g; the group is generated by shift-by-g
    orbit_sizes: tuple[int, ...]       # o_j per seed; effective rank k = sum
    initial_temperature: float = 0.5
    min_temperature: float = 1e-4
    cooling_rate: float = 0.999
    iterations_at_temp: int = 400
    reseed_prob: float = 0.02
    two_seed_prob: float = 0.2
    early_exit: float = 1e-12
    audit_every: int = 5000


def _residual(target: np.ndarray, columns: list[np.ndarray]):
    a = np.column_stack(columns)
    coeffs, *_ = np.linalg.lstsq(a, target, rcond=None)
    return float(np.linalg.norm(target - a @ coeffs)), coeffs


def _mutate_seed(
    seed: np.ndarray, period: int, n: int, p: int, rng: np.random.Generator
) -> np.ndarray:
    """One symmetry-preserving move: a gate replicated over period translates."""
    reps = n // period
    kind = rng.integers(0, 6)
    out = seed
    if kind in (0, 1, 2, 3):  # single-qudit gate at all translates of one site
        q0 = int(rng.integers(0, period))
        op = (apply_x, apply_z, apply_s, apply_f)[kind]
        for t in range(reps):
            out = op(out, q0 + t * period, n, p)
    elif kind == 4:  # CZ over all translates; may couple period blocks
        q0 = int(rng.integers(0, period))
        offset = int(rng.integers(1, n))
        pairs = {tuple(sorted(((q0 + t * period) % n, (q0 + t * period + offset) % n)))
                 for t in range(reps)}
        for a_, b_ in pairs:
            out = apply_cz(out, a_, b_, n, p)
    else:  # CX within a period block, replicated across blocks
        if period < 2:
            return _mutate_seed(seed, period, n, p, rng)
        q0, q1 = rng.choice(period, size=2, replace=False)
        for t in range(reps):
            out = apply_cx(out, int(q0) + t * period, int(q1) + t * period, n, p)
    return out


def run_symmetric_sa(
    target: np.ndarray,
    n: int,
    p: int,
    config: SymmetricSAConfig,
    seed: int = 0,
    verbose: bool = False,
):
    """Anneal seeds under the cyclic-orbit ansatz; returns (error, columns, coeffs)."""
    group_order = n // config.shift_unit
    if n % config.shift_unit != 0:
        raise ValueError("shift_unit must divide n")
    for o in config.orbit_sizes:
        if group_order % o != 0:
            raise ValueError("orbit sizes must divide the group order")

    rng = np.random.default_rng(seed)
    target = np.asarray(target, dtype=complex)
    periods = [config.shift_unit * o for o in config.orbit_sizes]
    seeds = [periodic_seed(n, p, per, rng) for per in periods]

    def all_columns(ss):
        cols = []
        for s_, o_ in zip(ss, config.orbit_sizes):
            cols.extend(orbit_columns(s_, o_, config.shift_unit, n, p))
        return cols

    current_err, coeffs = _residual(target, all_columns(seeds))
    best_err, best_seeds, best_coeffs = current_err, [s.copy() for s in seeds], coeffs

    temperature = config.initial_temperature
    iteration = 0
    while temperature > config.min_temperature and best_err > config.early_exit:
        for _ in range(config.iterations_at_temp):
            iteration += 1
            n_mut = 2 if (len(seeds) > 1 and rng.random() < config.two_seed_prob) else 1
            picks = rng.choice(len(seeds), size=n_mut, replace=False)
            saved = [(int(j), seeds[int(j)]) for j in picks]
            for j in picks:
                j = int(j)
                if rng.random() < config.reseed_prob:
                    seeds[j] = periodic_seed(n, p, periods[j], rng)
                else:
                    seeds[j] = _mutate_seed(seeds[j], periods[j], n, p, rng)
            new_err, new_coeffs = _residual(target, all_columns(seeds))
            delta = new_err - current_err
            if delta < 0 or rng.random() < math.exp(-delta / temperature):
                current_err = new_err
                if new_err < best_err:
                    best_err = new_err
                    best_seeds = [s.copy() for s in seeds]
                    best_coeffs = new_coeffs
                    for s_, per in zip(best_seeds, periods):
                        if not _is_periodic(s_, per, n, p):
                            raise RuntimeError(
                                "symmetry audit failed: seed lost its periodicity")
                    if best_err <= config.early_exit:
                        break
            else:
                for j, old in saved:
                    seeds[j] = old
            if iteration % config.audit_every == 0:
                for s_, per in zip(seeds, periods):
                    if not _is_periodic(s_, per, n, p):
                        raise RuntimeError(
                            "symmetry audit failed: seed lost its periodicity")
        if verbose and iteration % (config.iterations_at_temp * 50) == 0:
            print(f"  T={temperature:.5f} current={current_err:.6f} best={best_err:.6f}",
                  flush=True)
        temperature *= config.cooling_rate

    return best_err, all_columns(best_seeds), best_coeffs
