"""Field-theoretic lower bounds on the stabilizer rank of the T3 orbit.

Every qutrit stabilizer state is a positive real multiple of a vector with
entries in Z[w3], so the span of any exact stabilizer decomposition is defined
over Q(w3) and is therefore mapped to itself by any automorphism of C fixing
Q(w3), applied entrywise.

|T3> = (|0> + w9|1> + w9^2|2>)/sqrt(3) has entries in Q(w9), and

    Gal(Q(w9)/Q(w3)) = Z_3,  generated by  sigma: w9 -> w9 w3 = w9^4.

Writing t_a = (|0> + w9^a|1> + w9^{2a}|2>)/sqrt(3), the orbit of |T3> = t_1 is
{t_1, t_4, t_7}.  So for every m the span W of any decomposition of
|T3>^{ot m} contains

    V_m = span{ t_1^{ot m}, t_4^{ot m}, t_7^{ot m} },

whose dimension is 3 for every m (a Vandermonde in w9, w9^4, w9^7).  Two
consequences, both proved here:

  chi(|T3>^{ot m}) >= 3 for every m >= 1, with no search at all.  This is the
  only lower bound on the T3 orbit that holds for all m: the subset-sum
  technique needs an exponentially increasing subsequence of amplitude moduli,
  and all three amplitudes of |T3> have modulus 1/sqrt(3).

  chi(|T3>^{ot 3}) >= 5.  A rank-r span has dimension r and contains V_m, so
  the r states' components off V_m span at most r-3 dimensions.  For r=3 that
  forces a stabilizer state to lie inside V_3, and none does.  For r=4 it
  forces two of them to be parallel off V_3, and no two are.  Both checks are
  single-pass and are reported with their margins.

The same count run at m=2 recovers the known tight value as a positive control:
exactly three stabilizer states lie in V_2 and they are a rank-3 decomposition
of |T3>^{ot 2}.
"""
import functools
import os
import sys

import numpy as np

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from stabrank import qutrit_complex_magic_state
from stabrank.stabilizer_extent import enumerate_stabilizer_states

W9 = np.exp(2j * np.pi / 9)
TOL = 1e-9


def distinct_states(m: int) -> np.ndarray:
    """All m-qutrit stabilizer states, one column each, deduped up to phase.

    enumerate_stabilizer_states lists (subspace, coset, phase-polynomial)
    triples, and different triples can name the same state up to a global
    phase, so the raw list repeats states.  Global phase is irrelevant to a
    stabilizer decomposition, and a repeated state would look parallel to
    itself, so the duplicates are collapsed here.  The counts below match
    3^m prod_{j=1..m} (3^j + 1).
    """
    raw = enumerate_stabilizer_states(m, 3)
    S = raw if raw.shape[1] == 3**m else raw.T
    seen: dict[bytes, None] = {}
    keep: list[np.ndarray] = []
    for row in S:
        pivot = next(x for x in row if abs(x) > TOL)
        canon = np.round(row * (abs(pivot) / pivot), 6) + 0.0
        key = canon.real.tobytes() + canon.imag.tobytes()
        if key not in seen:
            seen[key] = None
            keep.append(row)
    return np.stack(keep, axis=1)


def galois_image(a: int, m: int) -> np.ndarray:
    """t_a^{ot m}, the image of |T3>^{ot m} under sigma^j with a = 4^j mod 9."""
    single = np.array([1.0, W9**a, W9 ** (2 * a)], dtype=complex) / np.sqrt(3)
    return functools.reduce(np.kron, [single] * m)


def galois_space(m: int) -> np.ndarray:
    """Orthonormal basis of V_m = span{t_1^m, t_4^m, t_7^m}."""
    V = np.stack([galois_image(a, m) for a in (1, 4, 7)], axis=1)
    Q, _ = np.linalg.qr(V)
    return Q


def main() -> None:
    print("sigma: w9 -> w9^4, so the Galois orbit of |T3> is {t_1, t_4, t_7}\n")

    print("dim V_m (a rank-r decomposition needs r >= dim V_m):")
    for m in range(1, 7):
        V = np.stack([galois_image(a, m) for a in (1, 4, 7)], axis=1)
        print(f"  m={m}: dim = {np.linalg.matrix_rank(V, tol=TOL)}"
              f"   =>  chi(|T3>^{{ot {m}}}) >= 3")
    print("  holds for every m, with no enumeration\n")

    for m in (2, 3):
        Q = galois_space(m)
        S = distinct_states(m)
        expected = 3**m
        for j in range(1, m + 1):
            expected *= 3**j + 1
        assert S.shape[1] == expected, (S.shape[1], expected)
        resid = S - Q @ (Q.conj().T @ S)
        off = np.linalg.norm(resid, axis=0)
        inside = int(np.sum(off < TOL))
        print(f"m={m}: {S.shape[1]} distinct stabilizer states, "
              f"{inside} of them inside V_{m}")

        if m == 2:
            idx = np.where(off < TOL)[0]
            A = S[:, idx]
            psi = qutrit_complex_magic_state(2)
            c, *_ = np.linalg.lstsq(A, psi, rcond=None)
            print(f"      positive control: those {len(idx)} states reproduce "
                  f"|T3>^{{ot 2}} with residual {np.linalg.norm(A @ c - psi):.2e}")
            print("      so chi(|T3>^{ot 2}) = 3, upper bound and lower bound both\n")
            continue

        print(f"      r=3 needs one inside V_3; smallest component off V_3 "
              f"is {off.min():.6f}")
        P = resid / off
        best = 0.0
        for a in range(0, P.shape[1], 2000):
            G = np.abs(P[:, a:a + 2000].conj().T @ P)
            for k in range(G.shape[0]):
                G[k, a + k] = 0.0
            best = max(best, float(G.max()))
        print(f"      r=4 needs two parallel off V_3; largest |<p_i,p_j>| "
              f"is {best:.10f}")
        if off.min() > TOL and best < 1 - 1e-6:
            print(f"      both margins are wide, so chi(|T3>^{{ot 3}}) >= 5")


if __name__ == "__main__":
    main()
