"""Certificate: chi(|T3>^{ot m}) >= 3 for every m, with no search.

Every qutrit stabilizer state is a positive real multiple of a vector over
Z[w3], so the span of an exact decomposition is defined over Q(w3) and is
mapped to itself by any automorphism of C fixing Q(w3).  |T3> lies in Q(w9),
and Gal(Q(w9)/Q(w3)) = Z_3 is generated by w9 -> w9 w3 = w9^4, so that span
contains V_m = span{t_1^m, t_4^m, t_7^m} with t_a = (|0>+w9^a|1>+w9^{2a}|2>).
dim V_m = 3 by a Vandermonde in w9, w9^4, w9^7, hence chi >= 3.

Printed claim: CERTIFIED chi(T3^m) >= 3
"""
import functools
import sympy as sp

w9 = sp.exp(2 * sp.pi * sp.I / 9)


def t(a):
    return sp.Matrix([1, w9 ** a, w9 ** (2 * a)]) / sp.sqrt(3)


def tp(v, m):
    out = v
    for _ in range(m - 1):
        out = sp.Matrix(sp.kronecker_product(out, v))
    return out


for m in range(1, 7):
    V = sp.Matrix.hstack(*[tp(t(a), m) for a in (1, 4, 7)])
    r = V.rank()
    assert r == 3, f"dim V_{m} = {r}, expected 3"
    print(f"  m={m}: dim V_m = {r}")
print("CERTIFIED chi(T3^m) >= 3")
