"""Slice-and-lift: a lower bound one copy up, from every minimal decomposition
one copy down.

Lemma (slice-and-lift). Let phi be a single-qutrit state with amplitudes
alpha_0, alpha_1, alpha_2, all nonzero, and let r = chi(phi^m). Suppose
phi^(m+1) = sum_i c_i s_i is a stabilizer decomposition with r terms, and
slice it along the first qutrit, u_i^(k) = (<k| (x) I) s_i. Then

  (a) for each k, phi^m = sum_i (c_i / alpha_k) u_i^(k), so every slice is a
      minimal decomposition of phi^m and no u_i^(k) vanishes;
  (b) for each term i there is a Pauli operator Q_i = X^a Z^c on m qutrits
      and cube roots of unity mu_i, nu_i with
          u_i^(2) = mu_i Q_i u_i^(1)   and   u_i^(0) = nu_i Q_i^-1 u_i^(1).

Proof of (b). The stabilizer group G_i of s_i has 3^(m+1) elements mod
phase. Its image under the projection to the symplectic coordinates (a_1,
c_1) of the first qutrit is a subgroup of F_3^2; the kernel consists of
elements I (x) Q and is abelian on m qutrits, so has at most 3^m elements,
so the image has order 3 or 9. If the image contains (1, b), G_i contains
lambda X Z^b (x) Q_i, and applying it to s_i gives u_i^(k+1) = lambda
w3^(b k) Q_i u_i^(k) for every k; lambda is a cube root of unity because
(X Z^b)^3 = I. If the image is generated by (0, 1), the kernel has 3^m
elements, so it is a maximal stabilizer group on m qutrits, s_i is a product
beta (x) v, all three slices are multiples of v with ratios that are cube
roots of unity by (a), and Q_i = I works. Both cases give the stated form
with mu_i = lambda w3^b, nu_i = lambda^-1.

Corollary. chi(phi^(m+1)) = r if and only if some minimal decomposition
(d_i, u_i) of phi^m lifts: there are Pauli classes Q_i mod Stab(u_i) and
cube roots mu_i, nu_i with
    sum_i d_i mu_i Q_i u_i = (alpha_2 / alpha_1) phi^m,
    sum_i d_i nu_i Q_i^-1 u_i = (alpha_0 / alpha_1) phi^m.
Conversely, given such data, s_i = |0> nu_i Q_i^-1 u_i + |1> u_i + |2>
mu_i Q_i u_i is stabilized by (X Z^b (x) Q_i) up to phase for the right b,
hence is a stabilizer state (its stabilizer group is the one generated by
that element and I (x) Stab(u_i), of full size), and sum_i alpha_1 d_i s_i
= phi^(m+1). Replacing Q_i by Q_i g with g in Stab(u_i) changes Q_i u_i not
at all and Q_i^-1 u_i by a phase, so Pauli classes suffice, and the two
equations decouple: the first is a finite matching over 3^m classes times 3
phases per term, solved by meet in the middle, and for each solution the
second is a linear solve whose coefficients must come out as cube roots.

Symmetry. A unitary symmetry U of phi^m (a local Clifford stabilizer of phi
on each copy, or a permutation of copies) acts on phi^(m+1) as I (x) U,
preserves slices, and carries lifts to lifts. So it suffices to test one
decomposition per orbit of the unitary symmetry group, and a pivot-pair
search from one pivot per orbit of the dictionary finds a member of every
orbit of decompositions (each decomposition contains some state; move that
state to its orbit representative). The antiunitary symmetry is not used: it
mixes slices.

Controls, run by `python slice_lift.py`: the rank-3 decompositions of |T3>
lift to |T3>^2 (rank stays 3 there), and the rank-3 decompositions of |N>^2
do not lift to |N>^3 (chi(N^3) = 4 by the exhaustive exclusion).
"""

from __future__ import annotations

import itertools
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rank_exclusion import (dictionary, psi_for, _parallel_groups,  # noqa: E402
                            symmetry_orbit_reps, PROJ_DIM)

W3 = np.exp(2j * np.pi / 3)
CUBE = np.array([1, W3, W3 ** 2])
TOL = 1e-7


# ------------------------------------------------------------- Paulis -----

def _digits(m):
    x = np.arange(3 ** m)
    return (x[:, None] // 3 ** (m - 1 - np.arange(m))[None, :]) % 3   # (dim, m)


def _canon_key(v):
    """Bytes identifying v up to a global phase (first nonzero entry made real
    positive); entries are exact roots of unity over a common modulus, so
    rounding to six places is stable."""
    j = np.flatnonzero(np.abs(v) > 1e-9)[0]
    w = v * (abs(v[j]) / v[j])
    return (np.round(w, 6) + 0.0).tobytes()


def pauli_images(u, m):
    """One (Q u, Q^-1 u) pair per Pauli class Q mod the stabilizer of u.

    Q = X^a Z^c acts by (Q u)[x + a] = w3^(c.x) u[x]; Q^-1 = Z^-c X^-a acts
    by (Q^-1 u)[x] = w3^(-c.x) u[x + a]. Different representatives of a class
    give the same Q u and Q^-1 u up to phase, and the phase is absorbed by
    nu, so one representative per distinct Q u suffices. Returns exactly 3^m
    pairs (the Pauli group mod phase has 3^(2m) elements and Stab(u) has 3^m).
    """
    dim = 3 ** m
    digs = _digits(m)
    seen = {}
    for a in itertools.product(range(3), repeat=m):
        y = ((digs + np.array(a)) % 3) @ (3 ** (m - 1 - np.arange(m)))
        for c in itertools.product(range(3), repeat=m):
            ph = W3 ** ((digs @ np.array(c)) % 3)
            qu = np.zeros(dim, dtype=complex)
            qu[y] = ph * u
            qinv = np.conj(ph) * u[y]
            key = _canon_key(qu)
            if key not in seen:
                seen[key] = (qu, qinv)
    pairs = list(seen.values())
    if len(pairs) != 3 ** m:
        raise AssertionError(f"{len(pairs)} Pauli images of a state on {m} qutrits, expected {3 ** m}")
    return pairs


# ------------------------------------------------------------- lifting -----

def _match_sums(L, R, rhs, tol=TOL):
    """Index pairs (l, r) with L[l] + R[r] = rhs within tol, by a random
    functional, a sort on its real part and a full check of every candidate."""
    rng = np.random.default_rng(5)
    f = rng.normal(size=L.shape[1]) + 1j * rng.normal(size=L.shape[1])
    kl = L @ f
    kr = (rhs[None, :] - R) @ f
    order = np.argsort(kl.real)
    kls = kl.real[order]
    # |f.(v - rhs)| <= |f| |v - rhs|_2 <= |f| sqrt(dim) |v - rhs|_inf, so every
    # combination within tol (entrywise) has its key inside this window
    ktol = tol * np.linalg.norm(f) * np.sqrt(L.shape[1])
    lo = np.searchsorted(kls, kr.real - ktol, side="left")
    hi = np.searchsorted(kls, kr.real + ktol, side="right")
    out = []
    for r in np.flatnonzero(hi > lo):
        for l in order[lo[r]:hi[r]]:
            if np.abs(L[l] + R[r] - rhs).max() < tol:
                out.append((int(l), int(r)))
    # A floor on how close any combination comes to the equation: the real
    # part of a key gap is at most |f| times the vector distance, so the
    # smallest real gap over all pairs, divided by |f|, is a lower bound.
    pos = np.clip(np.searchsorted(kls, kr.real), 1, len(kls) - 1)
    gaps = np.minimum(np.abs(kls[pos] - kr.real), np.abs(kls[pos - 1] - kr.real))
    floor = float(gaps.min() / np.linalg.norm(f)) if len(kls) > 1 else float("nan")
    return out, floor


def _sum_table(arrays):
    """All sums of one row from each array, with the mixed-radix combo index
    decoded by `_decode`."""
    S = arrays[0]
    for A in arrays[1:]:
        S = (S[:, None, :] + A[None, :, :]).reshape(-1, S.shape[1])
    return S


def _decode(idx, sizes):
    out = []
    for n in reversed(sizes):
        out.append(idx % n)
        idx //= n
    return list(reversed(out))


def lifts(dec_states, dec_coeffs, alpha, target_m, m, tol=TOL):
    """Every lift of the minimal decomposition target_m = sum d_i u_i of
    phi^m, taken as slice k = 1, to a rank-r decomposition of phi^(m+1).

    Returns a list of lifts, each a list of r stabilizer vectors of dimension
    3^(m+1), and the number of slice-2 matches examined.
    """
    r = len(dec_states)
    a0, a1, a2 = (complex(x) for x in alpha)
    rhs2 = (a2 / a1) * target_m
    rhs0 = (a0 / a1) * target_m
    imgs = [pauli_images(u, m) for u in dec_states]
    # slice-2 options: d_i mu Q u, one row per (class, mu)
    opts2 = [np.array([d * mu * qu for qu, _ in im for mu in CUBE]) for d, im in zip(dec_coeffs, imgs)]
    sizes = [len(o) for o in opts2]
    half = max(1, r // 2)
    L = _sum_table(opts2[:half])
    R = _sum_table(opts2[half:]) if r > half else np.zeros((1, len(target_m)), dtype=complex)
    matches, floor = _match_sums(L, R, rhs2, tol)
    found = []
    for l, rr in matches:
        combo = _decode(l, sizes[:half]) + (_decode(rr, sizes[half:]) if r > half else [])
        cls = [c // 3 for c in combo]
        mus = [CUBE[c % 3] for c in combo]
        # slice 0: sum d_i nu_i Q_i^-1 u_i = rhs0 with nu_i cube roots
        Qinv = np.column_stack([d * imgs[i][cls[i]][1] for i, d in enumerate(dec_coeffs)])
        nu, *_ = np.linalg.lstsq(Qinv, rhs0, rcond=None)
        if np.abs(Qinv @ nu - rhs0).max() > tol:
            continue
        if np.abs(nu ** 3 - 1).max() > 1e-6:
            continue
        terms = []
        for i in range(r):
            qu, qinv = imgs[i][cls[i]]
            terms.append(np.concatenate((nu[i] * qinv, dec_states[i], mus[i] * qu)))
        found.append(terms)
    return found, (len(matches), floor)


def confirm_lift(terms, alpha, target_m):
    """Residual of the best fit of phi (x) phi^m by the lifted terms, and a
    check that every term is a stabilizer state (it lies in the dictionary is
    not checked here; it is a stabilizer state by construction, see the
    module docstring)."""
    psi = np.kron(np.asarray(alpha, dtype=complex), target_m)
    A = np.column_stack(terms)
    x, *_ = np.linalg.lstsq(A, psi, rcond=None)
    return float(np.linalg.norm(A @ x - psi))


# ------------------------------------------------- enumerating decompositions

def decompositions_with_pivot(psi, D, i, rank, partners=None, rng=None):
    """Every rank-`rank` decomposition of psi (rank 2, 3 or 4) that contains
    dictionary state i and, for rank 4, a partner from `partners` (default:
    every other state), as sorted index tuples.

    Rank 4 quotients out psi, s_i and the partner s_j, then collects pairs
    whose images are parallel. Such a pair (a, b) has s_a - c s_b in
    span(psi, s_i, s_j); it is a decomposition exactly when the psi
    coefficient is nonzero, i.e. when s_a and s_b are not also parallel
    modulo span(s_i, s_j) alone. That second test is one small Gram matrix
    per group, and survivors are confirmed by an exact solve. The random
    projection can only lose speed, not decompositions: parallel vectors
    stay parallel under any linear map, and every candidate is checked in
    the full space.
    """
    rng = rng or np.random.default_rng(11)
    psi = psi / np.linalg.norm(psi)
    N, dim = D.shape[1], D.shape[0]
    R = rng.normal(size=(PROJ_DIM, dim)) + 1j * rng.normal(size=(PROJ_DIM, dim))
    B1, _ = np.linalg.qr(np.column_stack((psi, D[:, i])))
    q1 = D - B1 @ (B1.conj().T @ D)
    n1 = np.linalg.norm(q1, axis=0)
    found = set()

    def confirm(cols):
        A = D[:, list(cols)]
        if np.linalg.matrix_rank(A, tol=1e-8) < len(cols):
            return False
        x, *_ = np.linalg.lstsq(A, psi, rcond=None)
        return np.linalg.norm(A @ x - psi) < 1e-9

    if rank == 2:
        for j in np.flatnonzero(n1 < 1e-7):
            if j != i and confirm((i, int(j))):
                found.add(tuple(sorted((int(i), int(j)))))
        return sorted(found)
    if rank == 3:
        keep = n1 > 1e-7
        keep[i] = False
        ids = np.flatnonzero(keep)
        U = R @ q1[:, ids]
        U /= np.linalg.norm(U, axis=0)
        groups, _ = _parallel_groups(U, rng)
        for g in groups:
            gi = ids[g]
            for a in range(len(gi)):
                for b in range(a + 1, len(gi)):
                    cols = tuple(sorted((int(i), int(gi[a]), int(gi[b]))))
                    if confirm(cols):
                        found.add(cols)
        return sorted(found)
    if rank != 4:
        raise ValueError("rank must be 2, 3 or 4")
    # rank 4: the pivot's projection modulo span(s_i) only, for the psi-coefficient test
    e_i = D[:, i] / np.linalg.norm(D[:, i])
    p1 = D - np.outer(e_i, e_i.conj() @ D)
    partners = range(N) if partners is None else partners
    RQ1 = R @ q1
    for j in partners:
        if j == i or n1[j] < 1e-7:
            continue
        v = q1[:, j] / n1[j]
        w = v.conj() @ q1                       # components along the partner
        nq2 = np.sqrt(np.maximum(n1 ** 2 - np.abs(w) ** 2, 0))
        keep = nq2 > 1e-7
        keep[i] = keep[j] = False
        ids = np.flatnonzero(keep)
        U = RQ1[:, ids] - np.outer(R @ v, w[ids])
        U /= np.linalg.norm(U, axis=0)
        groups, _ = _parallel_groups(U, rng)
        if not groups:
            continue
        # projections modulo span(s_i, s_j) only
        f = p1[:, j] / np.linalg.norm(p1[:, j])
        for g in groups:
            gi = ids[g]
            P2 = p1[:, gi] - np.outer(f, f.conj() @ p1[:, gi])
            P2 /= np.linalg.norm(P2, axis=0)
            Gm = np.abs(P2.conj().T @ P2)
            for a in range(len(gi)):
                for b in range(a + 1, len(gi)):
                    if Gm[a, b] > 1 - 1e-6:
                        continue                # dependent quadruple, psi absent
                    cols = tuple(sorted((int(i), int(j), int(gi[a]), int(gi[b]))))
                    if confirm(cols):
                        found.add(cols)
    return sorted(found)


def all_decompositions(orbit, m, rank, D=None, verbose=True):
    """One member of every unitary-symmetry orbit of rank-`rank`
    decompositions of |M>^m (and possibly more), with the pivot list used."""
    import time
    from stabrank_verify import ORBIT_P
    D = dictionary(ORBIT_P[orbit], m) if D is None else D
    psi = psi_for(orbit, m)
    reps, info = symmetry_orbit_reps(orbit, m, D, antiunitary=False)
    if verbose:
        print(f"{orbit} m={m}: {D.shape[1]} states, unitary symmetry group of order "
              f"{info['order']}, {info['orbits']} pivot orbits", flush=True)
    # A decomposition is a multiset of orbits; move a member of its lowest
    # orbit (by representative index) to the pivot and the other members lie
    # in orbits with representative index at least the pivot's. So partners
    # can be restricted to those states.
    roots = info["roots"]
    out = set()
    for n, i in enumerate(np.sort(reps)):
        t = time.time()
        partners = np.flatnonzero(roots >= i) if rank == 4 else None
        decs = decompositions_with_pivot(psi, D, int(i), rank, partners=partners)
        out.update(decs)
        if verbose:
            print(f"  pivot {n + 1}/{len(reps)} (state {i}): {len(decs)} decompositions, "
                  f"{time.time() - t:.1f}s", flush=True)
    return sorted(out), reps


# ------------------------------------------------------------- qubits ------

FOURTH = np.array([1, 1j, -1, -1j])


def pauli_images_qubit(u, m):
    """One Q u per Pauli class Q mod the stabilizer of u, for Q = X^a Z^c on
    m qubits acting by (Q u)[x xor a] = (-1)^(c.x) u[x]. Exactly 2^m images."""
    dim = 1 << m
    x = np.arange(dim)
    seen = {}
    for a in range(dim):
        y = x ^ a
        for c in range(dim):
            ph = (-1.0) ** np.array([bin(c & t).count("1") for t in x])
            qu = np.zeros(dim, dtype=complex)
            qu[y] = ph * u
            key = _canon_key(qu)
            if key not in seen:
                seen[key] = qu
    imgs = list(seen.values())
    if len(imgs) != dim:
        raise AssertionError(f"{len(imgs)} Pauli images of a state on {m} qubits, expected {dim}")
    return imgs


def lifts_qubit(dec_states, dec_coeffs, alpha, target_m, m, tol=TOL):
    """Qubit version of `lifts`. With phi = alpha_0 |0> + alpha_1 |1>, both
    nonzero, a rank-r decomposition of phi^(m+1) sliced along the first qubit
    has slice 0 a minimal decomposition (d_i, u_i) of phi^m and slice 1 equal
    to mu_i Q_i u_i termwise, with Q_i a Pauli and mu_i a fourth root of
    unity: the stabilizer group of the term contains lambda X Z^b (x) Q_i
    (or the term is a product beta (x) v with beta of full support), and
    lambda^2 (X Z^b)^2 Q_i^2 = I forces lambda^4 = 1. Conversely
    |0> u + |1> mu Q u is a controlled-Pauli image of (|0> + mu |1>) (x) u,
    hence a stabilizer state. So the lift condition is the single matching
        sum_i d_i mu_i Q_i u_i = (alpha_1 / alpha_0) phi^m.
    """
    r = len(dec_states)
    a0, a1 = (complex(x) for x in alpha)
    rhs = (a1 / a0) * target_m
    imgs = [pauli_images_qubit(u, m) for u in dec_states]
    opts = [np.array([d * mu * qu for qu in im for mu in FOURTH]) for d, im in zip(dec_coeffs, imgs)]
    sizes = [len(o) for o in opts]
    half = max(1, r // 2)
    L = _sum_table(opts[:half])
    R = _sum_table(opts[half:]) if r > half else np.zeros((1, len(target_m)), dtype=complex)
    matches, floor = _match_sums(L, R, rhs, tol)
    found = []
    for l, rr in matches:
        combo = _decode(l, sizes[:half]) + (_decode(rr, sizes[half:]) if r > half else [])
        terms = [np.concatenate((dec_states[i], FOURTH[c % 4] * imgs[i][c // 4]))
                 for i, c in enumerate(combo)]
        found.append(terms)
    return found, (len(matches), floor)


def lift_all(orbit, m, decs, D, verbose=True):
    """Lift every decomposition in `decs` (index tuples into D) one copy up.
    Returns the list of lifted term lists; every lift is confirmed against
    phi (x) phi^m and a failure raises."""
    from stabrank_verify import orbit_state, ORBIT_P
    alpha = np.array([complex(x) for x in orbit_state(orbit)]).ravel()
    psi = psi_for(orbit, m)
    lifter = lifts if ORBIT_P[orbit] == 3 else lifts_qubit
    lifted, floor = [], float("inf")
    for cols in decs:
        states = [D[:, c] for c in cols]
        d, *_ = np.linalg.lstsq(np.column_stack(states), psi, rcond=None)
        if np.linalg.norm(np.column_stack(states) @ d - psi) > 1e-9:
            raise AssertionError("a listed decomposition does not reproduce the target")
        L, (nmatch, fl) = lifter(states, d, alpha, psi, m)
        if not L:
            floor = min(floor, fl)
        for terms in L:
            res = confirm_lift(terms, alpha, psi)
            if res > 1e-8:
                raise AssertionError(f"a lift failed its confirmation, residual {res:.2e}")
            lifted.append(terms)
    if verbose:
        print(f"{orbit} m={m} -> {m + 1}: {len(decs)} decompositions, {len(lifted)} lifts"
              + (f"; no unlifted decomposition comes within {floor:.2e} of the slice equation"
                 if floor < float("inf") else ""), flush=True)
    return lifted


if __name__ == "__main__":
    import time
    t0 = time.time()
    D1 = dictionary(3, 1)
    decs1, _ = all_decompositions("T3", 1, 3, D1, verbose=False)
    L1 = lift_all("T3", 1, decs1, D1, verbose=False)
    print(f"control 1: {len(decs1)} rank-3 decompositions of |T3>, {len(L1)} lifts to m=2 "
          f"(must be > 0) [{time.time() - t0:.1f}s]")
    t0 = time.time()
    D2 = dictionary(3, 2)
    decs2, _ = all_decompositions("N", 2, 3, D2, verbose=False)
    L2 = lift_all("N", 2, decs2, D2, verbose=False)
    print(f"control 2: {len(decs2)} rank-3 decompositions of |N>^2, {len(L2)} lifts to m=3 "
          f"(must be 0) [{time.time() - t0:.1f}s]")
    t0 = time.time()
    D3 = dictionary(2, 3)
    decs3, _ = all_decompositions("qubit_T", 3, 3, D3, verbose=False)
    L3 = lift_all("qubit_T", 3, decs3, D3, verbose=False)
    print(f"control 3: {len(decs3)} rank-3 decompositions of |T>^3, {len(L3)} lifts to m=4 "
          f"(must be > 0, chi(T^4) = 3) [{time.time() - t0:.1f}s]")
    t0 = time.time()
    D2q = dictionary(2, 2)
    decs4, _ = all_decompositions("qubit_H", 2, 2, D2q, verbose=False)
    L4 = lift_all("qubit_H", 2, decs4, D2q, verbose=False)
    print(f"control 4: {len(decs4)} rank-2 decompositions of |H>^2, {len(L4)} lifts to m=3 "
          f"(must be 0, chi(H^3) = 3) [{time.time() - t0:.1f}s]")
