/-
`χ(|qubit_H⟩^⊗6) ≤ 6` against `stabRankP 2`, from the witness of
`bounds/qubit_H-m6-upper-6.json`.

Generated by `lean_proofs/tools/gen_witness_lean.py`; do not edit by hand. The
terms are the file's, entered as `stabTerm 2 6 k x0 W Q l` with the pivot
columns of `W` (`Q` is read as an upper-triangular form, as the verifier reads
it). Each coefficient is the integer vector `Cj` in the basis `B4` of
`LeanProofs/ReflectQubit.lean`: the file's coefficient, divided by the
`√2^k` normalisation of its term and by the common scalar in front of the
target (`hVec_eq_ev`), times `Den = 1`. The pointwise identity is
decided by the kernel on integer vectors at all 64 digit strings (`key`) and
carried to `ℂ` by `ev_termZ`.
-/
import LeanProofs.ReflectQubit

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace QubitHM6

/-- The scalar in front of the target in `qubit_H` at `m = 6`. -/
noncomputable def scalar : ℂ := 1 / 4 ^ 3

def x0_0 : Fin 6 → ZMod 2 := ![0, 0, 0, 0, 0, 0]
def W0 : Fin 6 → Fin 6 → ZMod 2 := ![![1, 0, 0, 0, 0, 0], ![0, 1, 0, 0, 0, 0], ![0, 0, 1, 0, 0, 0], ![0, 0, 0, 1, 0, 0], ![0, 0, 0, 0, 1, 0], ![0, 0, 0, 0, 0, 1]]
def Q0 : Fin 6 → Fin 6 → ZMod 2 := ![![0, 1, 1, 1, 1, 1], ![0, 0, 1, 1, 1, 1], ![0, 0, 0, 1, 1, 1], ![0, 0, 0, 0, 1, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 0]]
def l0 : Fin 6 → ZMod (stabPeriod 2) := ![2, 2, 2, 2, 2, 2]
def piv0 : Fin 6 → Fin 6 := ![0, 1, 2, 3, 4, 5]
theorem piv0_ok : ∀ j j', W0 j (piv0 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t0 : Fin (2 ^ 6) → ℂ := stabTerm 2 6 6 x0_0 W0 Q0 l0
theorem t0_isStab : IsStabP 2 t0 :=
  isStabP_stabTerm 2 6 6 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv0 piv0_ok)
def C0 : Fin 4 → ℤ := ![0, (-2), 0, 0]

def x0_1 : Fin 6 → ZMod 2 := ![0, 0, 0, 0, 0, 0]
def W1 : Fin 1 → Fin 6 → ZMod 2 := ![![1, 1, 1, 1, 1, 1]]
def Q1 : Fin 1 → Fin 1 → ZMod 2 := ![![0]]
def l1 : Fin 1 → ZMod (stabPeriod 2) := ![2]
def piv1 : Fin 1 → Fin 6 := ![0]
theorem piv1_ok : ∀ j j', W1 j (piv1 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t1 : Fin (2 ^ 6) → ℂ := stabTerm 2 6 1 x0_1 W1 Q1 l1
theorem t1_isStab : IsStabP 2 t1 :=
  isStabP_stabTerm 2 6 1 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv1 piv1_ok)
def C1 : Fin 4 → ℤ := ![0, 16, 0, 0]

def x0_2 : Fin 6 → ZMod 2 := ![0, 0, 0, 0, 0, 1]
def W2 : Fin 5 → Fin 6 → ZMod 2 := ![![1, 0, 0, 0, 0, 1], ![0, 1, 0, 0, 0, 1], ![0, 0, 1, 0, 0, 1], ![0, 0, 0, 1, 0, 1], ![0, 0, 0, 0, 1, 1]]
def Q2 : Fin 5 → Fin 5 → ZMod 2 := ![![0, 0, 0, 0, 0], ![0, 0, 0, 0, 0], ![0, 0, 0, 0, 0], ![0, 0, 0, 0, 0], ![0, 0, 0, 0, 0]]
def l2 : Fin 5 → ZMod (stabPeriod 2) := ![0, 0, 0, 0, 0]
def piv2 : Fin 5 → Fin 6 := ![0, 1, 2, 3, 4]
theorem piv2_ok : ∀ j j', W2 j (piv2 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t2 : Fin (2 ^ 6) → ℂ := stabTerm 2 6 5 x0_2 W2 Q2 l2
theorem t2_isStab : IsStabP 2 t2 :=
  isStabP_stabTerm 2 6 5 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv2 piv2_ok)
def C2 : Fin 4 → ℤ := ![0, 4, 0, 0]

def x0_3 : Fin 6 → ZMod 2 := ![0, 0, 0, 0, 0, 1]
def W3 : Fin 5 → Fin 6 → ZMod 2 := ![![1, 0, 0, 0, 0, 1], ![0, 1, 0, 0, 0, 1], ![0, 0, 1, 0, 0, 1], ![0, 0, 0, 1, 0, 1], ![0, 0, 0, 0, 1, 1]]
def Q3 : Fin 5 → Fin 5 → ZMod 2 := ![![0, 1, 1, 1, 1], ![0, 0, 1, 1, 1], ![0, 0, 0, 1, 1], ![0, 0, 0, 0, 1], ![0, 0, 0, 0, 0]]
def l3 : Fin 5 → ZMod (stabPeriod 2) := ![2, 2, 2, 2, 2]
def piv3 : Fin 5 → Fin 6 := ![0, 1, 2, 3, 4]
theorem piv3_ok : ∀ j j', W3 j (piv3 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t3 : Fin (2 ^ 6) → ℂ := stabTerm 2 6 5 x0_3 W3 Q3 l3
theorem t3_isStab : IsStabP 2 t3 :=
  isStabP_stabTerm 2 6 5 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv3 piv3_ok)
def C3 : Fin 4 → ℤ := ![(-4), 0, 0, 0]

def x0_4 : Fin 6 → ZMod 2 := ![0, 0, 0, 0, 0, 0]
def W4 : Fin 6 → Fin 6 → ZMod 2 := ![![1, 0, 0, 0, 0, 0], ![0, 1, 0, 0, 0, 0], ![0, 0, 1, 0, 0, 0], ![0, 0, 0, 1, 0, 0], ![0, 0, 0, 0, 1, 0], ![0, 0, 0, 0, 0, 1]]
def Q4 : Fin 6 → Fin 6 → ZMod 2 := ![![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 0]]
def l4 : Fin 6 → ZMod (stabPeriod 2) := ![0, 0, 0, 0, 0, 2]
def piv4 : Fin 6 → Fin 6 := ![0, 1, 2, 3, 4, 5]
theorem piv4_ok : ∀ j j', W4 j (piv4 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t4 : Fin (2 ^ 6) → ℂ := stabTerm 2 6 6 x0_4 W4 Q4 l4
theorem t4_isStab : IsStabP 2 t4 :=
  isStabP_stabTerm 2 6 6 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv4 piv4_ok)
def C4 : Fin 4 → ℤ := ![4, 0, 0, 0]

def x0_5 : Fin 6 → ZMod 2 := ![0, 0, 0, 0, 0, 0]
def W5 : Fin 2 → Fin 6 → ZMod 2 := ![![1, 1, 1, 1, 1, 0], ![0, 0, 0, 0, 0, 1]]
def Q5 : Fin 2 → Fin 2 → ZMod 2 := ![![0, 1], ![0, 0]]
def l5 : Fin 2 → ZMod (stabPeriod 2) := ![2, 0]
def piv5 : Fin 2 → Fin 6 := ![0, 5]
theorem piv5_ok : ∀ j j', W5 j (piv5 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t5 : Fin (2 ^ 6) → ℂ := stabTerm 2 6 2 x0_5 W5 Q5 l5
theorem t5_isStab : IsStabP 2 t5 :=
  isStabP_stabTerm 2 6 2 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv5 piv5_ok)
def C5 : Fin 4 → ℤ := ![16, 0, 0, 0]

def Den : ℤ := 1

/-- The integer side of `Σ_j C_j · σ_j` at a digit string. -/
def rhsZ (x : Fin 6 → ZMod 2) : Fin 4 → ℤ :=
  termZ MI4 C0 x0_0 W0 Q0 l0 piv0 x
    + termZ MI4 C1 x0_1 W1 Q1 l1 piv1 x
    + termZ MI4 C2 x0_2 W2 Q2 l2 piv2 x
    + termZ MI4 C3 x0_3 W3 Q3 l3 piv3 x
    + termZ MI4 C4 x0_4 W4 Q4 l4 piv4 x
    + termZ MI4 C5 x0_5 W5 Q5 l5 piv5 x

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- The identity on integer vectors, decided by the kernel at every index. -/
theorem key : ∀ idx : Fin (2 ^ 6), Den • tgtH 6 (digitsP 2 6 idx) = rhsZ (digitsP 2 6 idx) := by
  decide +kernel

noncomputable def terms : Fin 6 → (Fin (2 ^ 6) → ℂ) :=
  ![t0, t1, t2, t3, t4, t5]
def Cs : Fin 6 → Fin 4 → ℤ := ![C0, C1, C2, C3, C4, C5]

theorem terms_isStab : ∀ j, IsStabP 2 (terms j) := by
  intro j
  fin_cases j
  exacts [t0_isStab, t1_isStab, t2_isStab, t3_isStab, t4_isStab, t5_isStab]

set_option linter.unusedSimpArgs false in
theorem target_eq : hVec 6 = ∑ j, (scalar * ev B4 (Cs j)) • terms j := by
  funext idx
  have hk := congrArg (ev B4) (key idx)
  rw [ev_zsmul] at hk
  simp only [rhsZ, ev_add, Den, Int.cast_one, Int.cast_ofNat, one_mul, ev_termZ B4 MI4_represents piv0_ok, ev_termZ B4 MI4_represents piv1_ok, ev_termZ B4 MI4_represents piv2_ok, ev_termZ B4 MI4_represents piv3_ok, ev_termZ B4 MI4_represents piv4_ok, ev_termZ B4 MI4_represents piv5_ok] at hk
  have ht : hVec 6 idx = scalar * ev B4 (tgtH 6 (digitsP 2 6 idx)) := by
    have h := hVec_eq_ev 6 idx
    try simp only [Nat.reduceMod, Nat.reduceDiv, pow_zero, pow_one] at h
    unfold scalar
    linear_combination h
  rw [Finset.sum_apply, ht]
  simp only [Pi.smul_apply, smul_eq_mul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, add_zero, terms, Cs, t0, t1, t2, t3, t4, t5, stabTerm]
  linear_combination scalar * hk

end QubitHM6

/-- **χ(|qubit_H⟩^⊗6) ≤ 6 against `IsStabP 2`.** -/
theorem qubit_h_m6_stabRankP_le_six : stabRankP 2 (hVec 6) ≤ 6 :=
  stabRankP_le_of_terms 2 QubitHM6.terms _ QubitHM6.terms_isStab QubitHM6.target_eq

end StabRank
