/-
Slice 0 of 8 of the kernel check of `QubitHM8StabRank`: the identity at
the indices `q * 32 + i`. Generated by
`lean_proofs/tools/gen_witness_lean.py`; do not edit by hand.
-/
import LeanProofs.QubitHM8Data

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace QubitHM8

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem key0 : ∀ i : Fin 32, Den • tgtH 8 (digitsP 2 8 (cidx ⟨0, by norm_num⟩ i)) = rhsZ (digitsP 2 8 (cidx ⟨0, by norm_num⟩ i)) := by
  decide +kernel

end QubitHM8

end StabRank
