/-
The data of `QubitHM8StabRank`: the terms, coefficient vectors and integer side of
the witness of `bounds/qubit_H-m8-upper-12.json`. Generated by
`lean_proofs/tools/gen_witness_lean.py`; do not edit by hand.
-/
import LeanProofs.ReflectQubit
import LeanProofs.Stabilizer.Chunks

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace QubitHM8

/-- The scalar in front of the target in `qubit_H` at `m = 8`. -/
noncomputable def scalar : ℂ := 1 / 4 ^ 4

def x0_0 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 0, 0, 0]
def W0 : Fin 7 → Fin 8 → ZMod 2 := ![![1, 0, 0, 0, 0, 0, 0, 1], ![0, 1, 0, 0, 0, 0, 0, 1], ![0, 0, 1, 0, 0, 0, 0, 1], ![0, 0, 0, 1, 0, 0, 0, 1], ![0, 0, 0, 0, 1, 0, 0, 1], ![0, 0, 0, 0, 0, 1, 0, 1], ![0, 0, 0, 0, 0, 0, 1, 1]]
def Q0 : Fin 7 → Fin 7 → ZMod 2 := ![![0, 1, 1, 1, 1, 0, 0], ![0, 0, 1, 1, 1, 0, 0], ![0, 0, 0, 1, 1, 0, 0], ![0, 0, 0, 0, 1, 0, 0], ![0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0]]
def l0 : Fin 7 → ZMod (stabPeriod 2) := ![2, 2, 2, 2, 2, 0, 0]
def piv0 : Fin 7 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6]
theorem piv0_ok : ∀ j j', W0 j (piv0 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t0 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 7 x0_0 W0 Q0 l0
theorem t0_isStab : IsStabP 2 t0 :=
  isStabP_stabTerm 2 8 7 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv0 piv0_ok)
def C0 : Fin 4 → ℤ := ![0, (-4), 0, 0]

def x0_1 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 0, 0, 0]
def W1 : Fin 8 → Fin 8 → ZMod 2 := ![![1, 0, 0, 0, 0, 0, 0, 0], ![0, 1, 0, 0, 0, 0, 0, 0], ![0, 0, 1, 0, 0, 0, 0, 0], ![0, 0, 0, 1, 0, 0, 0, 0], ![0, 0, 0, 0, 1, 0, 0, 0], ![0, 0, 0, 0, 0, 1, 0, 0], ![0, 0, 0, 0, 0, 0, 1, 0], ![0, 0, 0, 0, 0, 0, 0, 1]]
def Q1 : Fin 8 → Fin 8 → ZMod 2 := ![![0, 1, 1, 1, 1, 1, 1, 1], ![0, 0, 1, 1, 1, 1, 1, 1], ![0, 0, 0, 1, 1, 1, 1, 1], ![0, 0, 0, 0, 1, 1, 1, 1], ![0, 0, 0, 0, 0, 1, 1, 1], ![0, 0, 0, 0, 0, 0, 1, 1], ![0, 0, 0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 0, 0, 0]]
def l1 : Fin 8 → ZMod (stabPeriod 2) := ![0, 0, 0, 0, 0, 0, 0, 0]
def piv1 : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
theorem piv1_ok : ∀ j j', W1 j (piv1 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t1 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 8 x0_1 W1 Q1 l1
theorem t1_isStab : IsStabP 2 t1 :=
  isStabP_stabTerm 2 8 8 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv1 piv1_ok)
def C1 : Fin 4 → ℤ := ![(-4), 0, 0, 0]

def x0_2 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 1, 1, 1]
def W2 : Fin 5 → Fin 8 → ZMod 2 := ![![1, 0, 0, 0, 0, 1, 1, 1], ![0, 1, 0, 0, 0, 1, 1, 1], ![0, 0, 1, 0, 0, 1, 1, 1], ![0, 0, 0, 1, 0, 1, 1, 1], ![0, 0, 0, 0, 1, 1, 1, 1]]
def Q2 : Fin 5 → Fin 5 → ZMod 2 := ![![0, 1, 1, 1, 1], ![0, 0, 1, 1, 1], ![0, 0, 0, 1, 1], ![0, 0, 0, 0, 1], ![0, 0, 0, 0, 0]]
def l2 : Fin 5 → ZMod (stabPeriod 2) := ![0, 0, 0, 0, 0]
def piv2 : Fin 5 → Fin 8 := ![0, 1, 2, 3, 4]
theorem piv2_ok : ∀ j j', W2 j (piv2 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t2 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 5 x0_2 W2 Q2 l2
theorem t2_isStab : IsStabP 2 t2 :=
  isStabP_stabTerm 2 8 5 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv2 piv2_ok)
def C2 : Fin 4 → ℤ := ![0, 8, 0, 0]

def x0_3 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 1, 1, 1]
def W3 : Fin 5 → Fin 8 → ZMod 2 := ![![1, 0, 0, 0, 0, 1, 1, 1], ![0, 1, 0, 0, 0, 1, 1, 1], ![0, 0, 1, 0, 0, 1, 1, 1], ![0, 0, 0, 1, 0, 1, 1, 1], ![0, 0, 0, 0, 1, 1, 1, 1]]
def Q3 : Fin 5 → Fin 5 → ZMod 2 := ![![0, 1, 1, 1, 1], ![0, 0, 1, 1, 1], ![0, 0, 0, 1, 1], ![0, 0, 0, 0, 1], ![0, 0, 0, 0, 0]]
def l3 : Fin 5 → ZMod (stabPeriod 2) := ![2, 2, 2, 2, 2]
def piv3 : Fin 5 → Fin 8 := ![0, 1, 2, 3, 4]
theorem piv3_ok : ∀ j j', W3 j (piv3 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t3 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 5 x0_3 W3 Q3 l3
theorem t3_isStab : IsStabP 2 t3 :=
  isStabP_stabTerm 2 8 5 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv3 piv3_ok)
def C3 : Fin 4 → ℤ := ![(-16), 0, 0, 0]

def x0_4 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 0, 0, 0]
def W4 : Fin 8 → Fin 8 → ZMod 2 := ![![1, 0, 0, 0, 0, 0, 0, 0], ![0, 1, 0, 0, 0, 0, 0, 0], ![0, 0, 1, 0, 0, 0, 0, 0], ![0, 0, 0, 1, 0, 0, 0, 0], ![0, 0, 0, 0, 1, 0, 0, 0], ![0, 0, 0, 0, 0, 1, 0, 0], ![0, 0, 0, 0, 0, 0, 1, 0], ![0, 0, 0, 0, 0, 0, 0, 1]]
def Q4 : Fin 8 → Fin 8 → ZMod 2 := ![![0, 0, 0, 0, 0, 1, 1, 1], ![0, 0, 0, 0, 0, 1, 1, 1], ![0, 0, 0, 0, 0, 1, 1, 1], ![0, 0, 0, 0, 0, 1, 1, 1], ![0, 0, 0, 0, 0, 1, 1, 1], ![0, 0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0]]
def l4 : Fin 8 → ZMod (stabPeriod 2) := ![2, 2, 2, 2, 2, 2, 2, 2]
def piv4 : Fin 8 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6, 7]
theorem piv4_ok : ∀ j j', W4 j (piv4 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t4 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 8 x0_4 W4 Q4 l4
theorem t4_isStab : IsStabP 2 t4 :=
  isStabP_stabTerm 2 8 8 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv4 piv4_ok)
def C4 : Fin 4 → ℤ := ![0, (-4), 0, 0]

def x0_5 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 0, 0, 0]
def W5 : Fin 7 → Fin 8 → ZMod 2 := ![![1, 0, 0, 0, 0, 0, 0, 1], ![0, 1, 0, 0, 0, 0, 0, 1], ![0, 0, 1, 0, 0, 0, 0, 1], ![0, 0, 0, 1, 0, 0, 0, 1], ![0, 0, 0, 0, 1, 0, 0, 1], ![0, 0, 0, 0, 0, 1, 0, 1], ![0, 0, 0, 0, 0, 0, 1, 1]]
def Q5 : Fin 7 → Fin 7 → ZMod 2 := ![![0, 0, 0, 0, 0, 1, 1], ![0, 0, 0, 0, 0, 1, 1], ![0, 0, 0, 0, 0, 1, 1], ![0, 0, 0, 0, 0, 1, 1], ![0, 0, 0, 0, 0, 1, 1], ![0, 0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 0, 0]]
def l5 : Fin 7 → ZMod (stabPeriod 2) := ![2, 2, 2, 2, 2, 2, 2]
def piv5 : Fin 7 → Fin 8 := ![0, 1, 2, 3, 4, 5, 6]
theorem piv5_ok : ∀ j j', W5 j (piv5 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t5 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 7 x0_5 W5 Q5 l5
theorem t5_isStab : IsStabP 2 t5 :=
  isStabP_stabTerm 2 8 7 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv5 piv5_ok)
def C5 : Fin 4 → ℤ := ![(-8), 0, 0, 0]

def x0_6 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 0, 0, 0]
def W6 : Fin 6 → Fin 8 → ZMod 2 := ![![1, 0, 0, 0, 0, 0, 0, 0], ![0, 1, 0, 0, 0, 0, 0, 0], ![0, 0, 1, 0, 0, 0, 0, 0], ![0, 0, 0, 1, 0, 0, 0, 0], ![0, 0, 0, 0, 1, 0, 0, 0], ![0, 0, 0, 0, 0, 1, 1, 1]]
def Q6 : Fin 6 → Fin 6 → ZMod 2 := ![![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 0]]
def l6 : Fin 6 → ZMod (stabPeriod 2) := ![0, 0, 0, 0, 0, 0]
def piv6 : Fin 6 → Fin 8 := ![0, 1, 2, 3, 4, 5]
theorem piv6_ok : ∀ j j', W6 j (piv6 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t6 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 6 x0_6 W6 Q6 l6
theorem t6_isStab : IsStabP 2 t6 :=
  isStabP_stabTerm 2 8 6 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv6 piv6_ok)
def C6 : Fin 4 → ℤ := ![0, 8, 0, 0]

def x0_7 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 0, 0, 0]
def W7 : Fin 6 → Fin 8 → ZMod 2 := ![![1, 0, 0, 0, 0, 0, 0, 0], ![0, 1, 0, 0, 0, 0, 0, 0], ![0, 0, 1, 0, 0, 0, 0, 0], ![0, 0, 0, 1, 0, 0, 0, 0], ![0, 0, 0, 0, 1, 0, 0, 0], ![0, 0, 0, 0, 0, 1, 1, 1]]
def Q7 : Fin 6 → Fin 6 → ZMod 2 := ![![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 1], ![0, 0, 0, 0, 0, 0]]
def l7 : Fin 6 → ZMod (stabPeriod 2) := ![0, 0, 0, 0, 0, 2]
def piv7 : Fin 6 → Fin 8 := ![0, 1, 2, 3, 4, 5]
theorem piv7_ok : ∀ j j', W7 j (piv7 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t7 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 6 x0_7 W7 Q7 l7
theorem t7_isStab : IsStabP 2 t7 :=
  isStabP_stabTerm 2 8 6 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv7 piv7_ok)
def C7 : Fin 4 → ℤ := ![16, 0, 0, 0]

def x0_8 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 0, 0, 0]
def W8 : Fin 4 → Fin 8 → ZMod 2 := ![![1, 1, 1, 1, 1, 0, 0, 0], ![0, 0, 0, 0, 0, 1, 0, 0], ![0, 0, 0, 0, 0, 0, 1, 0], ![0, 0, 0, 0, 0, 0, 0, 1]]
def Q8 : Fin 4 → Fin 4 → ZMod 2 := ![![0, 1, 1, 1], ![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]]
def l8 : Fin 4 → ZMod (stabPeriod 2) := ![0, 0, 0, 0]
def piv8 : Fin 4 → Fin 8 := ![0, 5, 6, 7]
theorem piv8_ok : ∀ j j', W8 j (piv8 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t8 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 4 x0_8 W8 Q8 l8
theorem t8_isStab : IsStabP 2 t8 :=
  isStabP_stabTerm 2 8 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv8 piv8_ok)
def C8 : Fin 4 → ℤ := ![0, 16, 0, 0]

def x0_9 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 0, 0, 1]
def W9 : Fin 3 → Fin 8 → ZMod 2 := ![![1, 1, 1, 1, 1, 0, 0, 1], ![0, 0, 0, 0, 0, 1, 0, 1], ![0, 0, 0, 0, 0, 0, 1, 1]]
def Q9 : Fin 3 → Fin 3 → ZMod 2 := ![![0, 1, 1], ![0, 0, 1], ![0, 0, 0]]
def l9 : Fin 3 → ZMod (stabPeriod 2) := ![0, 0, 0]
def piv9 : Fin 3 → Fin 8 := ![0, 5, 6]
theorem piv9_ok : ∀ j j', W9 j (piv9 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t9 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 3 x0_9 W9 Q9 l9
theorem t9_isStab : IsStabP 2 t9 :=
  isStabP_stabTerm 2 8 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv9 piv9_ok)
def C9 : Fin 4 → ℤ := ![32, 0, 0, 0]

def x0_10 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 0, 0, 0]
def W10 : Fin 2 → Fin 8 → ZMod 2 := ![![1, 1, 1, 1, 1, 0, 0, 0], ![0, 0, 0, 0, 0, 1, 1, 1]]
def Q10 : Fin 2 → Fin 2 → ZMod 2 := ![![0, 1], ![0, 0]]
def l10 : Fin 2 → ZMod (stabPeriod 2) := ![2, 2]
def piv10 : Fin 2 → Fin 8 := ![0, 5]
theorem piv10_ok : ∀ j j', W10 j (piv10 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t10 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 2 x0_10 W10 Q10 l10
theorem t10_isStab : IsStabP 2 t10 :=
  isStabP_stabTerm 2 8 2 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv10 piv10_ok)
def C10 : Fin 4 → ℤ := ![0, 32, 0, 0]

def x0_11 : Fin 8 → ZMod 2 := ![0, 0, 0, 0, 0, 0, 0, 0]
def W11 : Fin 2 → Fin 8 → ZMod 2 := ![![1, 1, 1, 1, 1, 0, 0, 0], ![0, 0, 0, 0, 0, 1, 1, 1]]
def Q11 : Fin 2 → Fin 2 → ZMod 2 := ![![0, 1], ![0, 0]]
def l11 : Fin 2 → ZMod (stabPeriod 2) := ![2, 0]
def piv11 : Fin 2 → Fin 8 := ![0, 5]
theorem piv11_ok : ∀ j j', W11 j (piv11 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t11 : Fin (2 ^ 8) → ℂ := stabTerm 2 8 2 x0_11 W11 Q11 l11
theorem t11_isStab : IsStabP 2 t11 :=
  isStabP_stabTerm 2 8 2 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv11 piv11_ok)
def C11 : Fin 4 → ℤ := ![64, 0, 0, 0]

def Den : ℤ := 1

/-- The integer side of `Σ_j C_j · σ_j` at a digit string. -/
def rhsZ (x : Fin 8 → ZMod 2) : Fin 4 → ℤ :=
  termZ MI4 C0 x0_0 W0 Q0 l0 piv0 x
    + termZ MI4 C1 x0_1 W1 Q1 l1 piv1 x
    + termZ MI4 C2 x0_2 W2 Q2 l2 piv2 x
    + termZ MI4 C3 x0_3 W3 Q3 l3 piv3 x
    + termZ MI4 C4 x0_4 W4 Q4 l4 piv4 x
    + termZ MI4 C5 x0_5 W5 Q5 l5 piv5 x
    + termZ MI4 C6 x0_6 W6 Q6 l6 piv6 x
    + termZ MI4 C7 x0_7 W7 Q7 l7 piv7 x
    + termZ MI4 C8 x0_8 W8 Q8 l8 piv8 x
    + termZ MI4 C9 x0_9 W9 Q9 l9 piv9 x
    + termZ MI4 C10 x0_10 W10 Q10 l10 piv10 x
    + termZ MI4 C11 x0_11 W11 Q11 l11 piv11 x

/-- The index `q * 32 + i` of slice `q`. -/
def cidx (q : Fin 8) (i : Fin 32) : Fin (2 ^ 8) := chunkIdx (c := 8) (N := 32) q i

end QubitHM8

end StabRank
