/-
Slice 1 of 4 of the kernel check of `QubitHM10StabRank`: the identity at
the indices `q * 256 + i`. Generated by
`lean_proofs/tools/gen_witness_lean.py`; do not edit by hand.
-/
import LeanProofs.QubitHM10Data

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace QubitHM10

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem key1 : ∀ i : Fin 256, Den • tgtH 10 (digitsP 2 10 (cidx ⟨1, by norm_num⟩ i)) = rhsZ (digitsP 2 10 (cidx ⟨1, by norm_num⟩ i)) := by
  decide +kernel

end QubitHM10

end StabRank
