/-
`χ(|qubit_H⟩^⊗8) ≤ 12` against `stabRankP 2`, from the witness of
`bounds/qubit_H-m8-upper-12.json`.

Generated by `lean_proofs/tools/gen_witness_lean.py`; do not edit by hand. The
terms are the file's, entered as `stabTerm 2 8 k x0 W Q l` with the pivot
columns of `W` (`Q` is read as an upper-triangular form, as the verifier reads
it). Each coefficient is the integer vector `Cj` in the basis `B4` of
`LeanProofs/ReflectQubit.lean`: the file's coefficient, divided by the
`√2^k` normalisation of its term and by the common scalar in front of the
target (`hVec_eq_ev`), times `Den = 1`. The pointwise identity is
decided by the kernel on integer vectors at all 256 digit strings (`key`) and
carried to `ℂ` by `ev_termZ`.

The kernel check is split into 8 slices of 32 indices, one
module `QubitHM8Key<q>` each, on the data of `QubitHM8Data`; `forall_fin_of_chunks`
of `Stabilizer/Chunks.lean` puts them together here.
-/
import LeanProofs.QubitHM8Key0
import LeanProofs.QubitHM8Key1
import LeanProofs.QubitHM8Key2
import LeanProofs.QubitHM8Key3
import LeanProofs.QubitHM8Key4
import LeanProofs.QubitHM8Key5
import LeanProofs.QubitHM8Key6
import LeanProofs.QubitHM8Key7

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace QubitHM8

/-- The identity on integer vectors at every index, from the slices. -/
theorem key : ∀ idx : Fin (2 ^ 8), Den • tgtH 8 (digitsP 2 8 idx) = rhsZ (digitsP 2 8 idx) :=
  forall_fin_of_chunks (c := 8) (N := 32) _ (fun q => by
    fin_cases q
    exacts [key0, key1, key2, key3, key4, key5, key6, key7])

noncomputable def terms : Fin 12 → (Fin (2 ^ 8) → ℂ) :=
  ![t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11]
def Cs : Fin 12 → Fin 4 → ℤ := ![C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11]

theorem terms_isStab : ∀ j, IsStabP 2 (terms j) := by
  intro j
  fin_cases j
  exacts [t0_isStab, t1_isStab, t2_isStab, t3_isStab, t4_isStab, t5_isStab, t6_isStab, t7_isStab, t8_isStab, t9_isStab, t10_isStab, t11_isStab]

set_option linter.unusedSimpArgs false in
theorem target_eq : hVec 8 = ∑ j, (scalar * ev B4 (Cs j)) • terms j := by
  funext idx
  have hk := congrArg (ev B4) (key idx)
  rw [ev_zsmul] at hk
  simp only [rhsZ, ev_add, Den, Int.cast_one, Int.cast_ofNat, one_mul, ev_termZ B4 MI4_represents piv0_ok, ev_termZ B4 MI4_represents piv1_ok, ev_termZ B4 MI4_represents piv2_ok, ev_termZ B4 MI4_represents piv3_ok, ev_termZ B4 MI4_represents piv4_ok, ev_termZ B4 MI4_represents piv5_ok, ev_termZ B4 MI4_represents piv6_ok, ev_termZ B4 MI4_represents piv7_ok, ev_termZ B4 MI4_represents piv8_ok, ev_termZ B4 MI4_represents piv9_ok, ev_termZ B4 MI4_represents piv10_ok, ev_termZ B4 MI4_represents piv11_ok] at hk
  have ht : hVec 8 idx = scalar * ev B4 (tgtH 8 (digitsP 2 8 idx)) := by
    have h := hVec_eq_ev 8 idx
    try simp only [Nat.reduceMod, Nat.reduceDiv, pow_zero, pow_one] at h
    unfold scalar
    linear_combination h
  rw [Finset.sum_apply, ht]
  simp only [Pi.smul_apply, smul_eq_mul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, add_zero, terms, Cs, t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, stabTerm]
  linear_combination scalar * hk

end QubitHM8

/-- **χ(|qubit_H⟩^⊗8) ≤ 12 against `IsStabP 2`.** -/
theorem qubit_h_m8_stabRankP_le_twelve : stabRankP 2 (hVec 8) ≤ 12 :=
  stabRankP_le_of_terms 2 QubitHM8.terms _ QubitHM8.terms_isStab QubitHM8.target_eq

end StabRank
