/-
The bases and multiplication matrices of the reflection proofs.

Generated by `lean_proofs/tools/gen_witness_lean.py --bases`; do not edit by
hand. For each ring the witnesses live in, a ℤ-basis `B` of it as a vector of
complex numbers, and for each multiplier the cells need (the phase root of
unity `ζ`, and the factors of the target amplitudes), its integer matrix `M`
on that basis with the proof `Represents B M θ`. Each column identity is a
polynomial identity in the atoms modulo `√2² = 2`, `√3² = 3`, `i² = -1`,
`ω₃² = -1 - ω₃`, `ω₉⁶ = -ω₉³ - 1`, closed by `linear_combination` with the
cofactors found by polynomial division. `LeanProofs/ReflectQubit.lean` and
`LeanProofs/ReflectQutrit.lean` build the target lemmas on top of this.
-/
import LeanProofs.Stabilizer.Reflect
import LeanProofs.QubitShared
import LeanProofs.T3M2Pointwise

set_option linter.style.longLine false
set_option linter.unusedSimpArgs false

namespace StabRank

open Stabilizer

/-- The ninth cyclotomic relation, from `ω₉³ = ω₃` and `ω₃² + ω₃ + 1 = 0`. -/
theorem omega9_pow_six : omega9 ^ 6 = -omega9 ^ 3 - 1 := by
  have h := omega3_sq_add_omega3_add_one
  rw [← omega9_cube] at h
  linear_combination h

/-! ### `ℤ[√2, i]`, for the H-type qubit cells -/

/-- The basis `1, √2, i, i√2`. -/
noncomputable def B4 : Fin 4 → ℂ := ![1, (Real.sqrt 2 : ℂ), Complex.I, (Real.sqrt 2 : ℂ) * Complex.I]
theorem B4_zero : B4 ⟨0, by norm_num⟩ = 1 := rfl

/-- Multiplication by `i`. -/
def MI4 : Fin 4 → Fin 4 → ℤ :=
  ![![0, 0, (-1), 0], ![0, 0, 0, (-1)], ![1, 0, 0, 0], ![0, 1, 0, 0]]
theorem MI4_represents' : Represents B4 MI4 Complex.I := by
  have h2 := sqrt2_sq_c
  have h3 := sqrt3_sq_c
  have hI := Complex.I_sq
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_⟩
  all_goals simp only [B4, MI4, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((1 : ℂ)) * hI
    | linear_combination ((1 : ℂ) * (Real.sqrt 2 : ℂ)) * hI

/-- Multiplication by `1 + √2`, the ratio `cos(π/8) / sin(π/8)`. -/
def M1ps2 : Fin 4 → Fin 4 → ℤ :=
  ![![1, 2, 0, 0], ![1, 1, 0, 0], ![0, 0, 1, 2], ![0, 0, 1, 1]]
theorem M1ps2_represents' : Represents B4 M1ps2 (1 + (Real.sqrt 2 : ℂ)) := by
  have h2 := sqrt2_sq_c
  have h3 := sqrt3_sq_c
  have hI := Complex.I_sq
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_⟩
  all_goals simp only [B4, M1ps2, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((1 : ℂ)) * h2
    | linear_combination ((1 : ℂ) * Complex.I) * h2

/-- Multiplication by `2 - √2 = 4 sin²(π/8)`. -/
def M2ms2 : Fin 4 → Fin 4 → ℤ :=
  ![![2, (-2), 0, 0], ![(-1), 2, 0, 0], ![0, 0, 2, (-2)], ![0, 0, (-1), 2]]
theorem M2ms2_represents' : Represents B4 M2ms2 (2 - (Real.sqrt 2 : ℂ)) := by
  have h2 := sqrt2_sq_c
  have h3 := sqrt3_sq_c
  have hI := Complex.I_sq
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_⟩
  all_goals simp only [B4, M2ms2, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((-1 : ℂ)) * h2
    | linear_combination ((-1 : ℂ) * Complex.I) * h2

theorem MI4_represents : Represents B4 MI4 (zeta 2) := by
  rw [zeta_two]; exact MI4_represents'

/-! ### `ℤ[√2, √3, i]`, for the T-type qubit cells -/

/-- The basis `1, √2, √3, √2√3, i, i√2, i√3, i√2√3`. -/
noncomputable def B8 : Fin 8 → ℂ := ![1, (Real.sqrt 2 : ℂ), (Real.sqrt 3 : ℂ), (Real.sqrt 2 : ℂ) * (Real.sqrt 3 : ℂ), Complex.I, (Real.sqrt 2 : ℂ) * Complex.I, (Real.sqrt 3 : ℂ) * Complex.I, (Real.sqrt 2 : ℂ) * (Real.sqrt 3 : ℂ) * Complex.I]
theorem B8_zero : B8 ⟨0, by norm_num⟩ = 1 := rfl

/-- Multiplication by `i`. -/
def MI8 : Fin 8 → Fin 8 → ℤ :=
  ![![0, 0, 0, 0, (-1), 0, 0, 0], ![0, 0, 0, 0, 0, (-1), 0, 0], ![0, 0, 0, 0, 0, 0, (-1), 0], ![0, 0, 0, 0, 0, 0, 0, (-1)], ![1, 0, 0, 0, 0, 0, 0, 0], ![0, 1, 0, 0, 0, 0, 0, 0], ![0, 0, 1, 0, 0, 0, 0, 0], ![0, 0, 0, 1, 0, 0, 0, 0]]
theorem MI8_represents' : Represents B8 MI8 Complex.I := by
  have h2 := sqrt2_sq_c
  have h3 := sqrt3_sq_c
  have hI := Complex.I_sq
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  all_goals simp only [B8, MI8, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((1 : ℂ)) * hI
    | linear_combination ((1 : ℂ) * (Real.sqrt 2 : ℂ)) * hI
    | linear_combination ((1 : ℂ) * (Real.sqrt 3 : ℂ)) * hI
    | linear_combination ((1 : ℂ) * (Real.sqrt 2 : ℂ) * (Real.sqrt 3 : ℂ)) * hI

/-- Multiplication by `√2(√3 + 1) = 2 cos β / sin β`. -/
def Ma8 : Fin 8 → Fin 8 → ℤ :=
  ![![0, 2, 0, 6, 0, 0, 0, 0], ![1, 0, 3, 0, 0, 0, 0, 0], ![0, 2, 0, 2, 0, 0, 0, 0], ![1, 0, 1, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 2, 0, 6], ![0, 0, 0, 0, 1, 0, 3, 0], ![0, 0, 0, 0, 0, 2, 0, 2], ![0, 0, 0, 0, 1, 0, 1, 0]]
theorem Ma8_represents' : Represents B8 Ma8 ((Real.sqrt 2 : ℂ) * (Real.sqrt 3 : ℂ) + (Real.sqrt 2 : ℂ)) := by
  have h2 := sqrt2_sq_c
  have h3 := sqrt3_sq_c
  have hI := Complex.I_sq
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  all_goals simp only [B8, Ma8, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((1 : ℂ) + (1 : ℂ) * (Real.sqrt 3 : ℂ)) * h2
    | linear_combination ((1 : ℂ) * (Real.sqrt 2 : ℂ)) * h3
    | linear_combination ((1 : ℂ) * (Real.sqrt 3 : ℂ) + (1 : ℂ) * (Real.sqrt 3 : ℂ) ^ 2) * h2 + ((2 : ℂ)) * h3
    | linear_combination ((1 : ℂ) * Complex.I + (1 : ℂ) * (Real.sqrt 3 : ℂ) * Complex.I) * h2
    | linear_combination ((1 : ℂ) * (Real.sqrt 2 : ℂ) * Complex.I) * h3
    | linear_combination ((1 : ℂ) * (Real.sqrt 3 : ℂ) * Complex.I + (1 : ℂ) * (Real.sqrt 3 : ℂ) ^ 2 * Complex.I) * h2 + ((2 : ℂ) * Complex.I) * h3

/-- Multiplication by `√2(1 + i) = 2 e^{iπ/4}`. -/
def Mb8 : Fin 8 → Fin 8 → ℤ :=
  ![![0, 2, 0, 0, 0, (-2), 0, 0], ![1, 0, 0, 0, (-1), 0, 0, 0], ![0, 0, 0, 2, 0, 0, 0, (-2)], ![0, 0, 1, 0, 0, 0, (-1), 0], ![0, 2, 0, 0, 0, 2, 0, 0], ![1, 0, 0, 0, 1, 0, 0, 0], ![0, 0, 0, 2, 0, 0, 0, 2], ![0, 0, 1, 0, 0, 0, 1, 0]]
theorem Mb8_represents' : Represents B8 Mb8 ((Real.sqrt 2 : ℂ) + Complex.I * (Real.sqrt 2 : ℂ)) := by
  have h2 := sqrt2_sq_c
  have h3 := sqrt3_sq_c
  have hI := Complex.I_sq
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  all_goals simp only [B8, Mb8, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((1 : ℂ) + (1 : ℂ) * Complex.I) * h2
    | linear_combination ((1 : ℂ) * (Real.sqrt 3 : ℂ) + (1 : ℂ) * (Real.sqrt 3 : ℂ) * Complex.I) * h2
    | linear_combination ((1 : ℂ) * (Real.sqrt 2 : ℂ)) * hI
    | linear_combination ((1 : ℂ) * Complex.I + (1 : ℂ) * Complex.I ^ 2) * h2 + ((2 : ℂ)) * hI
    | linear_combination ((1 : ℂ) * (Real.sqrt 2 : ℂ) * (Real.sqrt 3 : ℂ)) * hI
    | linear_combination ((1 : ℂ) * (Real.sqrt 3 : ℂ) * Complex.I + (1 : ℂ) * (Real.sqrt 3 : ℂ) * Complex.I ^ 2) * h2 + ((2 : ℂ) * (Real.sqrt 3 : ℂ)) * hI

/-- Multiplication by `3 - √3 = 6 sin² β`. -/
def Mc8 : Fin 8 → Fin 8 → ℤ :=
  ![![3, 0, (-3), 0, 0, 0, 0, 0], ![0, 3, 0, (-3), 0, 0, 0, 0], ![(-1), 0, 3, 0, 0, 0, 0, 0], ![0, (-1), 0, 3, 0, 0, 0, 0], ![0, 0, 0, 0, 3, 0, (-3), 0], ![0, 0, 0, 0, 0, 3, 0, (-3)], ![0, 0, 0, 0, (-1), 0, 3, 0], ![0, 0, 0, 0, 0, (-1), 0, 3]]
theorem Mc8_represents' : Represents B8 Mc8 (3 - (Real.sqrt 3 : ℂ)) := by
  have h2 := sqrt2_sq_c
  have h3 := sqrt3_sq_c
  have hI := Complex.I_sq
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  all_goals simp only [B8, Mc8, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((-1 : ℂ)) * h3
    | linear_combination ((-1 : ℂ) * (Real.sqrt 2 : ℂ)) * h3
    | linear_combination ((-1 : ℂ) * Complex.I) * h3
    | linear_combination ((-1 : ℂ) * (Real.sqrt 2 : ℂ) * Complex.I) * h3

theorem MI8_represents : Represents B8 MI8 (zeta 2) := by
  rw [zeta_two]; exact MI8_represents'

/-! ### `ℤ[ω₃, √3]`, for the H₃ cells -/

/-- The basis `1, ω₃, √3, √3 ω₃`. -/
noncomputable def B3 : Fin 4 → ℂ := ![1, omega3, (Real.sqrt 3 : ℂ), omega3 * (Real.sqrt 3 : ℂ)]
theorem B3_zero : B3 ⟨0, by norm_num⟩ = 1 := rfl

/-- Multiplication by `ω₃`. -/
def Mw3 : Fin 4 → Fin 4 → ℤ :=
  ![![0, (-1), 0, 0], ![1, (-1), 0, 0], ![0, 0, 0, (-1)], ![0, 0, 1, (-1)]]
theorem Mw3_represents' : Represents B3 Mw3 omega3 := by
  have h3 := sqrt3_sq_c
  have hw3 := omega3_sq_eq
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_⟩
  all_goals simp only [B3, Mw3, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((1 : ℂ)) * hw3
    | linear_combination ((1 : ℂ) * (Real.sqrt 3 : ℂ)) * hw3

/-- Multiplication by `3 + √3`, six times the `|0⟩` amplitude over `N`. -/
def M3ps3 : Fin 4 → Fin 4 → ℤ :=
  ![![3, 0, 3, 0], ![0, 3, 0, 3], ![1, 0, 3, 0], ![0, 1, 0, 3]]
theorem M3ps3_represents' : Represents B3 M3ps3 (3 + (Real.sqrt 3 : ℂ)) := by
  have h3 := sqrt3_sq_c
  have hw3 := omega3_sq_eq
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_⟩
  all_goals simp only [B3, M3ps3, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((1 : ℂ)) * h3
    | linear_combination ((1 : ℂ) * omega3) * h3

/-- Multiplication by `√3`, six times the `|1⟩`, `|2⟩` amplitude over `N`. -/
def Ms3 : Fin 4 → Fin 4 → ℤ :=
  ![![0, 0, 3, 0], ![0, 0, 0, 3], ![1, 0, 0, 0], ![0, 1, 0, 0]]
theorem Ms3_represents' : Represents B3 Ms3 (Real.sqrt 3 : ℂ) := by
  have h3 := sqrt3_sq_c
  have hw3 := omega3_sq_eq
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_⟩
  all_goals simp only [B3, Ms3, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((1 : ℂ)) * h3
    | linear_combination ((1 : ℂ) * omega3) * h3

/-- Multiplication by `3 - √3 = N²`. -/
def M3ms3 : Fin 4 → Fin 4 → ℤ :=
  ![![3, 0, (-3), 0], ![0, 3, 0, (-3)], ![(-1), 0, 3, 0], ![0, (-1), 0, 3]]
theorem M3ms3_represents' : Represents B3 M3ms3 (3 - (Real.sqrt 3 : ℂ)) := by
  have h3 := sqrt3_sq_c
  have hw3 := omega3_sq_eq
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_⟩
  all_goals simp only [B3, M3ms3, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((-1 : ℂ)) * h3
    | linear_combination ((-1 : ℂ) * omega3) * h3

theorem Mw3_represents : Represents B3 Mw3 (zeta 3) := by
  rw [zeta_three]; exact Mw3_represents'

/-! ### `ℤ[ω₉, √3]`, for the T₃ cells -/

/-- The basis `ω₉^t` and `√3 ω₉^t` for `t < 6`. -/
noncomputable def B9 : Fin 12 → ℂ := ![1, omega9, omega9 ^ 2, omega9 ^ 3, omega9 ^ 4, omega9 ^ 5, (Real.sqrt 3 : ℂ), omega9 * (Real.sqrt 3 : ℂ), omega9 ^ 2 * (Real.sqrt 3 : ℂ), omega9 ^ 3 * (Real.sqrt 3 : ℂ), omega9 ^ 4 * (Real.sqrt 3 : ℂ), omega9 ^ 5 * (Real.sqrt 3 : ℂ)]
theorem B9_zero : B9 ⟨0, by norm_num⟩ = 1 := rfl

/-- Multiplication by `ω₉`. -/
def Mw9 : Fin 12 → Fin 12 → ℤ :=
  ![![0, 0, 0, 0, 0, (-1), 0, 0, 0, 0, 0, 0], ![1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ![0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ![0, 0, 1, 0, 0, (-1), 0, 0, 0, 0, 0, 0], ![0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (-1)], ![0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, (-1)], ![0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]]
theorem Mw9_represents' : Represents B9 Mw9 omega9 := by
  have h3 := sqrt3_sq_c
  have hw9 := omega9_pow_six
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  all_goals simp only [B9, Mw9, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((1 : ℂ)) * hw9
    | linear_combination ((1 : ℂ) * (Real.sqrt 3 : ℂ)) * hw9

/-- Multiplication by `ω₉³ = ω₃`. -/
def Mw9c : Fin 12 → Fin 12 → ℤ :=
  ![![0, 0, 0, (-1), 0, 0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, (-1), 0, 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, (-1), 0, 0, 0, 0, 0, 0], ![1, 0, 0, (-1), 0, 0, 0, 0, 0, 0, 0, 0], ![0, 1, 0, 0, (-1), 0, 0, 0, 0, 0, 0, 0], ![0, 0, 1, 0, 0, (-1), 0, 0, 0, 0, 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0, 0, (-1), 0, 0], ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (-1), 0], ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (-1)], ![0, 0, 0, 0, 0, 0, 1, 0, 0, (-1), 0, 0], ![0, 0, 0, 0, 0, 0, 0, 1, 0, 0, (-1), 0], ![0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, (-1)]]
theorem Mw9c_represents' : Represents B9 Mw9c (omega9 ^ 3) := by
  have h3 := sqrt3_sq_c
  have hw9 := omega9_pow_six
  simp only [Represents, Fin.forall_fin_succ, IsEmpty.forall_iff, and_true]
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  all_goals simp only [B9, Mw9c, Fin.sum_univ_succ, Fin.sum_univ_zero,
    Matrix.cons_val_zero, Matrix.cons_val_succ, Int.cast_zero, Int.cast_one, Int.cast_neg,
    Int.cast_ofNat]
  all_goals first
    | ring1
    | linear_combination ((1 : ℂ)) * hw9
    | linear_combination ((1 : ℂ) * omega9) * hw9
    | linear_combination ((1 : ℂ) * omega9 ^ 2) * hw9
    | linear_combination ((1 : ℂ) * (Real.sqrt 3 : ℂ)) * hw9
    | linear_combination ((1 : ℂ) * omega9 * (Real.sqrt 3 : ℂ)) * hw9
    | linear_combination ((1 : ℂ) * omega9 ^ 2 * (Real.sqrt 3 : ℂ)) * hw9

theorem Mw9c_represents : Represents B9 Mw9c (zeta 3) := by
  rw [zeta_three, ← omega9_cube]; exact Mw9c_represents'

end StabRank
