/-
The data of `StrangeM5StabRank`: the terms, coefficient vectors and integer side of
the witness of `bounds/S-m5-upper-8.json`. Generated by
`lean_proofs/tools/gen_witness_lean.py`; do not edit by hand.
-/
import LeanProofs.ReflectQutrit
import LeanProofs.Stabilizer.Chunks

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace StrangeM5

/-- The scalar in front of the target in `S` at `m = 5`. -/
noncomputable def scalar : ℂ := (1 / (Real.sqrt 2 : ℂ)) ^ 5

def x0_0 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 1]
def W0 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0]]
def Q0 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 1, 0, 0], ![0, 1, 0, 0], ![0, 0, 1, 1], ![0, 0, 0, 1]]
def l0 : Fin 4 → ZMod (stabPeriod 3) := ![0, 0, 0, 0]
def piv0 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv0_ok : ∀ j j', W0 j (piv0 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t0 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_0 W0 Q0 l0
theorem t0_isStab : IsStabP 3 t0 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv0 piv0_ok)
def C0 : Fin 4 → ℤ := ![1, 1, 0, 0]

def x0_1 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 2]
def W1 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0]]
def Q1 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 1, 0, 0], ![0, 1, 0, 0], ![0, 0, 1, 1], ![0, 0, 0, 1]]
def l1 : Fin 4 → ZMod (stabPeriod 3) := ![0, 0, 0, 0]
def piv1 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv1_ok : ∀ j j', W1 j (piv1 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t1 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_1 W1 Q1 l1
theorem t1_isStab : IsStabP 3 t1 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv1 piv1_ok)
def C1 : Fin 4 → ℤ := ![(-1), (-1), 0, 0]

def x0_2 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 1]
def W2 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0]]
def Q2 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 1, 0, 0], ![0, 1, 0, 0], ![0, 0, 1, 2], ![0, 0, 0, 1]]
def l2 : Fin 4 → ZMod (stabPeriod 3) := ![0, 0, 0, 0]
def piv2 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv2_ok : ∀ j j', W2 j (piv2 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t2 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_2 W2 Q2 l2
theorem t2_isStab : IsStabP 3 t2 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv2 piv2_ok)
def C2 : Fin 4 → ℤ := ![(-1), (-1), 0, 0]

def x0_3 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 2]
def W3 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0]]
def Q3 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 1, 0, 0], ![0, 1, 0, 0], ![0, 0, 1, 2], ![0, 0, 0, 1]]
def l3 : Fin 4 → ZMod (stabPeriod 3) := ![0, 0, 0, 0]
def piv3 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv3_ok : ∀ j j', W3 j (piv3 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t3 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_3 W3 Q3 l3
theorem t3_isStab : IsStabP 3 t3 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv3 piv3_ok)
def C3 : Fin 4 → ℤ := ![1, 1, 0, 0]

def x0_4 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 1]
def W4 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0]]
def Q4 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 2, 0, 0], ![0, 1, 0, 0], ![0, 0, 1, 1], ![0, 0, 0, 1]]
def l4 : Fin 4 → ZMod (stabPeriod 3) := ![0, 0, 0, 0]
def piv4 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv4_ok : ∀ j j', W4 j (piv4 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t4 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_4 W4 Q4 l4
theorem t4_isStab : IsStabP 3 t4 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv4 piv4_ok)
def C4 : Fin 4 → ℤ := ![(-1), (-1), 0, 0]

def x0_5 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 2]
def W5 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0]]
def Q5 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 2, 0, 0], ![0, 1, 0, 0], ![0, 0, 1, 1], ![0, 0, 0, 1]]
def l5 : Fin 4 → ZMod (stabPeriod 3) := ![0, 0, 0, 0]
def piv5 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv5_ok : ∀ j j', W5 j (piv5 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t5 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_5 W5 Q5 l5
theorem t5_isStab : IsStabP 3 t5 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv5 piv5_ok)
def C5 : Fin 4 → ℤ := ![1, 1, 0, 0]

def x0_6 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 1]
def W6 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0]]
def Q6 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 2, 0, 0], ![0, 1, 0, 0], ![0, 0, 1, 2], ![0, 0, 0, 1]]
def l6 : Fin 4 → ZMod (stabPeriod 3) := ![0, 0, 0, 0]
def piv6 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv6_ok : ∀ j j', W6 j (piv6 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t6 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_6 W6 Q6 l6
theorem t6_isStab : IsStabP 3 t6 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv6 piv6_ok)
def C6 : Fin 4 → ℤ := ![1, 1, 0, 0]

def x0_7 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 2]
def W7 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 0], ![0, 1, 0, 0, 0], ![0, 0, 1, 0, 0], ![0, 0, 0, 1, 0]]
def Q7 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 2, 0, 0], ![0, 1, 0, 0], ![0, 0, 1, 2], ![0, 0, 0, 1]]
def l7 : Fin 4 → ZMod (stabPeriod 3) := ![0, 0, 0, 0]
def piv7 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv7_ok : ∀ j j', W7 j (piv7 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t7 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_7 W7 Q7 l7
theorem t7_isStab : IsStabP 3 t7 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv7 piv7_ok)
def C7 : Fin 4 → ℤ := ![(-1), (-1), 0, 0]

def Den : ℤ := 3

/-- The integer side of `Σ_j C_j · σ_j` at a digit string. -/
def rhsZ (x : Fin 5 → ZMod 3) : Fin 4 → ℤ :=
  termZ Mw3 C0 x0_0 W0 Q0 l0 piv0 x
    + termZ Mw3 C1 x0_1 W1 Q1 l1 piv1 x
    + termZ Mw3 C2 x0_2 W2 Q2 l2 piv2 x
    + termZ Mw3 C3 x0_3 W3 Q3 l3 piv3 x
    + termZ Mw3 C4 x0_4 W4 Q4 l4 piv4 x
    + termZ Mw3 C5 x0_5 W5 Q5 l5 piv5 x
    + termZ Mw3 C6 x0_6 W6 Q6 l6 piv6 x
    + termZ Mw3 C7 x0_7 W7 Q7 l7 piv7 x

/-- The index `q * 27 + i` of slice `q`. -/
def cidx (q : Fin 9) (i : Fin 27) : Fin (3 ^ 5) := chunkIdx (c := 9) (N := 27) q i

end StrangeM5

end StabRank
