/-
`χ(|S⟩^⊗5) ≤ 8` against `stabRankP 3`, from the witness of
`bounds/S-m5-upper-8.json`.

Generated by `lean_proofs/tools/gen_witness_lean.py`; do not edit by hand. The
terms are the file's, entered as `stabTerm 3 5 k x0 W Q l` with the pivot
columns of `W` (`Q` is read as an upper-triangular form, as the verifier reads
it). Each coefficient is the integer vector `Cj` in the basis `B3` of
`LeanProofs/ReflectQutrit.lean`: the file's coefficient, divided by the
`√3^k` normalisation of its term and by the common scalar in front of the
target (`strangeVec_eq_ev`), times `Den = 3`. The pointwise identity is
decided by the kernel on integer vectors at all 243 digit strings (`key`) and
carried to `ℂ` by `ev_termZ`.

The kernel check is split into 9 slices of 27 indices, one
module `StrangeM5Key<q>` each, on the data of `StrangeM5Data`; `forall_fin_of_chunks`
of `Stabilizer/Chunks.lean` puts them together here.
-/
import LeanProofs.StrangeM5Key0
import LeanProofs.StrangeM5Key1
import LeanProofs.StrangeM5Key2
import LeanProofs.StrangeM5Key3
import LeanProofs.StrangeM5Key4
import LeanProofs.StrangeM5Key5
import LeanProofs.StrangeM5Key6
import LeanProofs.StrangeM5Key7
import LeanProofs.StrangeM5Key8

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace StrangeM5

/-- The identity on integer vectors at every index, from the slices. -/
theorem key : ∀ idx : Fin (3 ^ 5), Den • tgtS 5 (digitsP 3 5 idx) = rhsZ (digitsP 3 5 idx) :=
  forall_fin_of_chunks (c := 9) (N := 27) _ (fun q => by
    fin_cases q
    exacts [key0, key1, key2, key3, key4, key5, key6, key7, key8])

noncomputable def terms : Fin 8 → (Fin (3 ^ 5) → ℂ) :=
  ![t0, t1, t2, t3, t4, t5, t6, t7]
def Cs : Fin 8 → Fin 4 → ℤ := ![C0, C1, C2, C3, C4, C5, C6, C7]

theorem terms_isStab : ∀ j, IsStabP 3 (terms j) := by
  intro j
  fin_cases j
  exacts [t0_isStab, t1_isStab, t2_isStab, t3_isStab, t4_isStab, t5_isStab, t6_isStab, t7_isStab]

set_option linter.unusedSimpArgs false in
theorem target_eq : strangeVec 5 = ∑ j, (scalar / 3 * ev B3 (Cs j)) • terms j := by
  funext idx
  have hk := congrArg (ev B3) (key idx)
  rw [ev_zsmul] at hk
  simp only [rhsZ, ev_add, Den, Int.cast_one, Int.cast_ofNat, one_mul, ev_termZ B3 Mw3_represents piv0_ok, ev_termZ B3 Mw3_represents piv1_ok, ev_termZ B3 Mw3_represents piv2_ok, ev_termZ B3 Mw3_represents piv3_ok, ev_termZ B3 Mw3_represents piv4_ok, ev_termZ B3 Mw3_represents piv5_ok, ev_termZ B3 Mw3_represents piv6_ok, ev_termZ B3 Mw3_represents piv7_ok] at hk
  have ht : strangeVec 5 idx = scalar * ev B3 (tgtS 5 (digitsP 3 5 idx)) := by
    have h := strangeVec_eq_ev 5 idx
    try simp only [Nat.reduceMod, Nat.reduceDiv, pow_zero, pow_one] at h
    unfold scalar
    linear_combination h
  rw [Finset.sum_apply, ht]
  simp only [Pi.smul_apply, smul_eq_mul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, add_zero, terms, Cs, t0, t1, t2, t3, t4, t5, t6, t7, stabTerm]
  linear_combination (scalar / 3) * hk

end StrangeM5

/-- **χ(|S⟩^⊗5) ≤ 8 against `IsStabP 3`.** -/
theorem strange_m5_stabRankP_le_eight : stabRankP 3 (strangeVec 5) ≤ 8 :=
  stabRankP_le_of_terms 3 StrangeM5.terms _ StrangeM5.terms_isStab StrangeM5.target_eq

/-- The same bound against the qutrit predicate `IsStab`. -/
theorem strange_m5_stabRank_le_eight : Stabilizer.stabRank (IsStab (n := 5)) (strangeVec 5) ≤ 8 := by
  rw [stabRank_eq_stabRankP]
  exact strange_m5_stabRankP_le_eight

end StabRank
