/-
Slice 3 of 9 of the kernel check of `StrangeM5StabRank`: the identity at
the indices `q * 27 + i`. Generated by
`lean_proofs/tools/gen_witness_lean.py`; do not edit by hand.
-/
import LeanProofs.StrangeM5Data

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace StrangeM5

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem key3 : ∀ i : Fin 27, Den • tgtS 5 (digitsP 3 5 (cidx ⟨3, by norm_num⟩ i)) = rhsZ (digitsP 3 5 (cidx ⟨3, by norm_num⟩ i)) := by
  decide +kernel

end StrangeM5

end StabRank
