/-
The dimension core of the Galois lower bound for the T3 orbit.

The argument for χ(|T3⟩^⊗m) ≥ 3 runs as follows. Every qutrit stabilizer state
is a positive real multiple of a vector over Z[ω₃], so a decomposition of
|T3⟩^⊗m into stabilizer states has all its terms over Q(ω₃). Solvability of a
linear system does not depend on the ambient field, so the coefficients may be
taken in Q(ω₉) as well, and then every σ ∈ Gal(Q(ω₉)/Q(ω₃)) ≅ Z₃ carries the
decomposition to another decomposition over the same terms. That group is
generated by ω₉ ↦ ω₉⁴, so the span of any decomposition contains the whole
Galois orbit of the target, namely t₁, t₄, t₇ with t_a having entries ω₉^(a·i).
Those three are linearly independent, so no decomposition has fewer than three
terms.

This file proves the last step, which is the part that carries the "3": the
Galois conjugates are independent because their coordinate matrix is a
Vandermonde matrix in ω₉, ω₉⁴, ω₉⁷, and those are distinct since ω₉ is a
primitive 9th root of unity.

What is NOT here is the descent: that stabilizer states are defined over
Z[ω₃], and that the span of a decomposition is therefore Galois-stable. Both
are real formalization work (the first needs stabilizer states as a Lean
definition rather than as the shape of a term), and without them this file does
not yet yield χ ≥ 3. It is the dimension count that argument ends on.
-/
import LeanProofs.T3M2Pointwise
import Mathlib.LinearAlgebra.Vandermonde
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse

namespace StabRank

open Complex

/-- Exponents of the Galois orbit of `ω₉` under `Gal(Q(ω₉)/Q(ω₃))`, which is
    generated by `ω₉ ↦ ω₉⁴`: starting from 1 gives 1, 4, 7 (mod 9). -/
def galoisExp : Fin 3 → ℕ := ![1, 4, 7]

/-- The three Galois conjugates of the (unnormalised) `|T3⟩` amplitude vector.
    `tConj a i = ω₉^(e_a · i)`, so `tConj 0` is `|T3⟩` itself up to `√3`. -/
noncomputable def tConj (a : Fin 3) : Fin 3 → ℂ :=
  fun i => omega9 ^ (galoisExp a * (i : ℕ))

/-- `ω₉ = exp(2πi/9)` is a primitive 9th root of unity. -/
theorem omega9_primitive : IsPrimitiveRoot omega9 9 := by
  have h := Complex.isPrimitiveRoot_exp 9 (by norm_num)
  have : ((9 : ℕ) : ℂ) = (9 : ℂ) := by norm_num
  rwa [this] at h

/-- The conjugates are pairwise distinct as powers of `ω₉`. -/
theorem omega9_pow_galoisExp_injective :
    Function.Injective (fun a : Fin 3 => omega9 ^ galoisExp a) := by
  intro a b hab
  have ha : galoisExp a < 9 := by fin_cases a <;> simp [galoisExp]
  have hb : galoisExp b < 9 := by fin_cases b <;> simp [galoisExp]
  have := omega9_primitive.pow_inj ha hb hab
  fin_cases a <;> fin_cases b <;> simp_all [galoisExp]

/-- The coordinate matrix of the conjugates is Vandermonde in `ω₉^(e_a)`. -/
theorem tConj_eq_vandermonde :
    (Matrix.of fun a i => tConj a i)
      = Matrix.vandermonde (fun a : Fin 3 => omega9 ^ galoisExp a) := by
  ext a i
  simp [tConj, Matrix.vandermonde, pow_mul]

/-- The Vandermonde determinant is nonzero, since the nodes are distinct. -/
theorem tConj_det_ne_zero :
    (Matrix.of fun a i => tConj a i).det ≠ 0 := by
  rw [tConj_eq_vandermonde, Matrix.det_vandermonde]
  refine Finset.prod_ne_zero_iff.mpr ?_
  intro i _
  refine Finset.prod_ne_zero_iff.mpr ?_
  intro j hj
  have hij : i ≠ j := by
    intro h
    rw [h] at hj
    exact absurd (Finset.mem_Ioi.mp hj) (lt_irrefl _)
  intro hzero
  exact hij (omega9_pow_galoisExp_injective (sub_eq_zero.mp hzero)).symm

/-- **The dimension count behind χ(|T3⟩) ≥ 3**: the three Galois conjugates of
    the T3 amplitude vector are linearly independent over ℂ, so any subspace
    containing the Galois orbit has dimension at least 3. -/
theorem tConj_linearIndependent : LinearIndependent ℂ tConj := by
  have hdet := tConj_det_ne_zero
  have : IsUnit (Matrix.of fun a i => tConj a i) := by
    rw [Matrix.isUnit_iff_isUnit_det]
    exact isUnit_iff_ne_zero.mpr hdet
  simpa using (Matrix.linearIndependent_rows_iff_isUnit.mpr this)

end StabRank
