/-
`χ(|T3⟩^⊗3) ≤ 8` against `stabRankP 3`, from the witness of
`bounds/T3-m3-upper-8.json`.

Generated by `lean_proofs/tools/gen_witness_lean.py`; do not edit by hand. The
terms are the file's, entered as `stabTerm 3 3 k x0 W Q l` with the pivot
columns of `W` (`Q` is read as an upper-triangular form, as the verifier reads
it). Each coefficient is the integer vector `Cj` in the basis `B9` of
`LeanProofs/ReflectQutrit.lean`: the file's coefficient, divided by the
`√3^k` normalisation of its term and by the common scalar in front of the
target (`t3TargetM_eq_ev`), times `Den = 3`. The pointwise identity is
decided by the kernel on integer vectors at all 27 digit strings (`key`) and
carried to `ℂ` by `ev_termZ`.
-/
import LeanProofs.ReflectQutrit

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace T3M3

/-- The scalar in front of the target in `T3` at `m = 3`. -/
noncomputable def scalar : ℂ := ((1 / Real.sqrt 3 : ℝ) : ℂ) ^ 3

def x0_0 : Fin 3 → ZMod 3 := ![0, 0, 0]
def W0 : Fin 3 → Fin 3 → ZMod 3 := ![![1, 0, 0], ![0, 1, 0], ![0, 0, 1]]
def Q0 : Fin 3 → Fin 3 → ZMod 3 := ![![0, 1, 1], ![0, 1, 2], ![0, 0, 1]]
def l0 : Fin 3 → ZMod (stabPeriod 3) := ![1, 0, 0]
def piv0 : Fin 3 → Fin 3 := ![0, 1, 2]
theorem piv0_ok : ∀ j j', W0 j (piv0 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t0 : Fin (3 ^ 3) → ℂ := stabTerm 3 3 3 x0_0 W0 Q0 l0
theorem t0_isStab : IsStabP 3 t0 :=
  isStabP_stabTerm 3 3 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv0 piv0_ok)
def C0 : Fin 12 → ℤ := ![1, 0, 0, (-1), 0, 0, 0, 0, 0, 0, 0, 0]

def x0_1 : Fin 3 → ZMod 3 := ![0, 1, 1]
def W1 : Fin 1 → Fin 3 → ZMod 3 := ![![1, 1, 1]]
def Q1 : Fin 1 → Fin 1 → ZMod 3 := ![![1]]
def l1 : Fin 1 → ZMod (stabPeriod 3) := ![1]
def piv1 : Fin 1 → Fin 3 := ![0]
theorem piv1_ok : ∀ j j', W1 j (piv1 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t1 : Fin (3 ^ 3) → ℂ := stabTerm 3 3 1 x0_1 W1 Q1 l1
theorem t1_isStab : IsStabP 3 t1 :=
  isStabP_stabTerm 3 3 1 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv1 piv1_ok)
def C1 : Fin 12 → ℤ := ![0, 3, 0, (-3), 3, (-3), 0, 0, 0, 0, 0, 0]

def x0_2 : Fin 3 → ZMod 3 := ![0, 0, 0]
def W2 : Fin 3 → Fin 3 → ZMod 3 := ![![1, 0, 0], ![0, 1, 0], ![0, 0, 1]]
def Q2 : Fin 3 → Fin 3 → ZMod 3 := ![![2, 1, 1], ![0, 0, 2], ![0, 0, 0]]
def l2 : Fin 3 → ZMod (stabPeriod 3) := ![1, 0, 0]
def piv2 : Fin 3 → Fin 3 := ![0, 1, 2]
theorem piv2_ok : ∀ j j', W2 j (piv2 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t2 : Fin (3 ^ 3) → ℂ := stabTerm 3 3 3 x0_2 W2 Q2 l2
theorem t2_isStab : IsStabP 3 t2 :=
  isStabP_stabTerm 3 3 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv2 piv2_ok)
def C2 : Fin 12 → ℤ := ![2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]

def x0_3 : Fin 3 → ZMod 3 := ![0, 0, 0]
def W3 : Fin 3 → Fin 3 → ZMod 3 := ![![1, 0, 0], ![0, 1, 0], ![0, 0, 1]]
def Q3 : Fin 3 → Fin 3 → ZMod 3 := ![![2, 2, 2], ![0, 2, 2], ![0, 0, 2]]
def l3 : Fin 3 → ZMod (stabPeriod 3) := ![2, 2, 2]
def piv3 : Fin 3 → Fin 3 := ![0, 1, 2]
theorem piv3_ok : ∀ j j', W3 j (piv3 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t3 : Fin (3 ^ 3) → ℂ := stabTerm 3 3 3 x0_3 W3 Q3 l3
theorem t3_isStab : IsStabP 3 t3 :=
  isStabP_stabTerm 3 3 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv3 piv3_ok)
def C3 : Fin 12 → ℤ := ![0, (-2), 0, 0, (-1), 0, 0, 0, 0, 0, 0, 0]

def x0_4 : Fin 3 → ZMod 3 := ![0, 1, 1]
def W4 : Fin 1 → Fin 3 → ZMod 3 := ![![1, 1, 1]]
def Q4 : Fin 1 → Fin 1 → ZMod 3 := ![![1]]
def l4 : Fin 1 → ZMod (stabPeriod 3) := ![2]
def piv4 : Fin 1 → Fin 3 := ![0]
theorem piv4_ok : ∀ j j', W4 j (piv4 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t4 : Fin (3 ^ 3) → ℂ := stabTerm 3 3 1 x0_4 W4 Q4 l4
theorem t4_isStab : IsStabP 3 t4 :=
  isStabP_stabTerm 3 3 1 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv4 piv4_ok)
def C4 : Fin 12 → ℤ := ![0, (-3), 0, 3, (-3), 3, 0, 0, 0, 0, 0, 0]

def x0_5 : Fin 3 → ZMod 3 := ![0, 0, 0]
def W5 : Fin 3 → Fin 3 → ZMod 3 := ![![1, 0, 0], ![0, 1, 0], ![0, 0, 1]]
def Q5 : Fin 3 → Fin 3 → ZMod 3 := ![![2, 0, 0], ![0, 2, 0], ![0, 0, 2]]
def l5 : Fin 3 → ZMod (stabPeriod 3) := ![0, 0, 0]
def piv5 : Fin 3 → Fin 3 := ![0, 1, 2]
theorem piv5_ok : ∀ j j', W5 j (piv5 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t5 : Fin (3 ^ 3) → ℂ := stabTerm 3 3 3 x0_5 W5 Q5 l5
theorem t5_isStab : IsStabP 3 t5 :=
  isStabP_stabTerm 3 3 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv5 piv5_ok)
def C5 : Fin 12 → ℤ := ![1, 1, 0, (-1), 2, 0, 0, 0, 0, 0, 0, 0]

def x0_6 : Fin 3 → ZMod 3 := ![0, 0, 0]
def W6 : Fin 3 → Fin 3 → ZMod 3 := ![![1, 0, 0], ![0, 1, 0], ![0, 0, 1]]
def Q6 : Fin 3 → Fin 3 → ZMod 3 := ![![2, 1, 1], ![0, 2, 1], ![0, 0, 2]]
def l6 : Fin 3 → ZMod (stabPeriod 3) := ![2, 2, 2]
def piv6 : Fin 3 → Fin 3 := ![0, 1, 2]
theorem piv6_ok : ∀ j j', W6 j (piv6 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t6 : Fin (3 ^ 3) → ℂ := stabTerm 3 3 3 x0_6 W6 Q6 l6
theorem t6_isStab : IsStabP 3 t6 :=
  isStabP_stabTerm 3 3 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv6 piv6_ok)
def C6 : Fin 12 → ℤ := ![(-1), 1, 0, 1, (-1), 0, 0, 0, 0, 0, 0, 0]

def x0_7 : Fin 3 → ZMod 3 := ![0, 0, 2]
def W7 : Fin 2 → Fin 3 → ZMod 3 := ![![1, 0, 2], ![0, 1, 2]]
def Q7 : Fin 2 → Fin 2 → ZMod 3 := ![![2, 0], ![0, 0]]
def l7 : Fin 2 → ZMod (stabPeriod 3) := ![1, 0]
def piv7 : Fin 2 → Fin 3 := ![0, 1]
theorem piv7_ok : ∀ j j', W7 j (piv7 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t7 : Fin (3 ^ 3) → ℂ := stabTerm 3 3 2 x0_7 W7 Q7 l7
theorem t7_isStab : IsStabP 3 t7 :=
  isStabP_stabTerm 3 3 2 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv7 piv7_ok)
def C7 : Fin 12 → ℤ := ![0, 0, 3, (-3), 3, 0, 0, 0, 0, 0, 0, 0]

def Den : ℤ := 3

/-- The integer side of `Σ_j C_j · σ_j` at a digit string. -/
def rhsZ (x : Fin 3 → ZMod 3) : Fin 12 → ℤ :=
  termZ Mw9c C0 x0_0 W0 Q0 l0 piv0 x
    + termZ Mw9c C1 x0_1 W1 Q1 l1 piv1 x
    + termZ Mw9c C2 x0_2 W2 Q2 l2 piv2 x
    + termZ Mw9c C3 x0_3 W3 Q3 l3 piv3 x
    + termZ Mw9c C4 x0_4 W4 Q4 l4 piv4 x
    + termZ Mw9c C5 x0_5 W5 Q5 l5 piv5 x
    + termZ Mw9c C6 x0_6 W6 Q6 l6 piv6 x
    + termZ Mw9c C7 x0_7 W7 Q7 l7 piv7 x

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- The identity on integer vectors, decided by the kernel at every index. -/
theorem key : ∀ idx : Fin (3 ^ 3), Den • tgtT3 3 idx = rhsZ (digitsP 3 3 idx) := by
  decide +kernel

noncomputable def terms : Fin 8 → (Fin (3 ^ 3) → ℂ) :=
  ![t0, t1, t2, t3, t4, t5, t6, t7]
def Cs : Fin 8 → Fin 12 → ℤ := ![C0, C1, C2, C3, C4, C5, C6, C7]

theorem terms_isStab : ∀ j, IsStabP 3 (terms j) := by
  intro j
  fin_cases j
  exacts [t0_isStab, t1_isStab, t2_isStab, t3_isStab, t4_isStab, t5_isStab, t6_isStab, t7_isStab]

set_option linter.unusedSimpArgs false in
theorem target_eq : t3TargetM 3 = ∑ j, (scalar / 3 * ev B9 (Cs j)) • terms j := by
  funext idx
  have hk := congrArg (ev B9) (key idx)
  rw [ev_zsmul] at hk
  simp only [rhsZ, ev_add, Den, Int.cast_one, Int.cast_ofNat, one_mul, ev_termZ B9 Mw9c_represents piv0_ok, ev_termZ B9 Mw9c_represents piv1_ok, ev_termZ B9 Mw9c_represents piv2_ok, ev_termZ B9 Mw9c_represents piv3_ok, ev_termZ B9 Mw9c_represents piv4_ok, ev_termZ B9 Mw9c_represents piv5_ok, ev_termZ B9 Mw9c_represents piv6_ok, ev_termZ B9 Mw9c_represents piv7_ok] at hk
  have ht : t3TargetM 3 idx = scalar * ev B9 (tgtT3 3 idx) := by
    have h := t3TargetM_eq_ev 3 idx
    try simp only [Nat.reduceMod, Nat.reduceDiv, pow_zero, pow_one] at h
    unfold scalar
    linear_combination h
  rw [Finset.sum_apply, ht]
  simp only [Pi.smul_apply, smul_eq_mul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, add_zero, terms, Cs, t0, t1, t2, t3, t4, t5, t6, t7, stabTerm]
  linear_combination (scalar / 3) * hk

end T3M3

/-- **χ(|T3⟩^⊗3) ≤ 8 against `IsStabP 3`.** -/
theorem t3_m3_stabRankP_le_eight : stabRankP 3 (t3TargetM 3) ≤ 8 :=
  stabRankP_le_of_terms 3 T3M3.terms _ T3M3.terms_isStab T3M3.target_eq

/-- The same bound against the qutrit predicate `IsStab`. -/
theorem t3_m3_stabRank_le_eight : Stabilizer.stabRank (IsStab (n := 3)) (t3TargetM 3) ≤ 8 := by
  rw [stabRank_eq_stabRankP]
  exact t3_m3_stabRankP_le_eight

end StabRank
