/-
`χ(|T3⟩^⊗5) ≤ 18` against `stabRankP 3`, from the witness of
`bounds/T3-m5-upper-18.json`.

Generated by `lean_proofs/tools/gen_witness_lean.py`; do not edit by hand. The
terms are the file's, entered as `stabTerm 3 5 k x0 W Q l` with the pivot
columns of `W` (`Q` is read as an upper-triangular form, as the verifier reads
it). Each coefficient is the integer vector `Cj` in the basis `B9` of
`LeanProofs/ReflectQutrit.lean`: the file's coefficient, divided by the
`√3^k` normalisation of its term and by the common scalar in front of the
target (`t3TargetM_eq_ev`), times `Den = 3`. The pointwise identity is
decided by the kernel on integer vectors at all 243 digit strings (`key`) and
carried to `ℂ` by `ev_termZ`.

The kernel check is split into 9 slices of 27 indices, one
module `T3M5Key<q>` each, on the data of `T3M5Data`; `forall_fin_of_chunks`
of `Stabilizer/Chunks.lean` puts them together here.
-/
import LeanProofs.T3M5Key0
import LeanProofs.T3M5Key1
import LeanProofs.T3M5Key2
import LeanProofs.T3M5Key3
import LeanProofs.T3M5Key4
import LeanProofs.T3M5Key5
import LeanProofs.T3M5Key6
import LeanProofs.T3M5Key7
import LeanProofs.T3M5Key8

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace T3M5

/-- The identity on integer vectors at every index, from the slices. -/
theorem key : ∀ idx : Fin (3 ^ 5), Den • tgtT3 5 idx = rhsZ (digitsP 3 5 idx) :=
  forall_fin_of_chunks (c := 9) (N := 27) _ (fun q => by
    fin_cases q
    exacts [key0, key1, key2, key3, key4, key5, key6, key7, key8])

noncomputable def terms : Fin 18 → (Fin (3 ^ 5) → ℂ) :=
  ![t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17]
def Cs : Fin 18 → Fin 12 → ℤ := ![C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16, C17]

theorem terms_isStab : ∀ j, IsStabP 3 (terms j) := by
  intro j
  fin_cases j
  exacts [t0_isStab, t1_isStab, t2_isStab, t3_isStab, t4_isStab, t5_isStab, t6_isStab, t7_isStab, t8_isStab, t9_isStab, t10_isStab, t11_isStab, t12_isStab, t13_isStab, t14_isStab, t15_isStab, t16_isStab, t17_isStab]

set_option linter.unusedSimpArgs false in
theorem target_eq : t3TargetM 5 = ∑ j, (scalar / 3 * ev B9 (Cs j)) • terms j := by
  funext idx
  have hk := congrArg (ev B9) (key idx)
  rw [ev_zsmul] at hk
  simp only [rhsZ, ev_add, Den, Int.cast_one, Int.cast_ofNat, one_mul, ev_termZ B9 Mw9c_represents piv0_ok, ev_termZ B9 Mw9c_represents piv1_ok, ev_termZ B9 Mw9c_represents piv2_ok, ev_termZ B9 Mw9c_represents piv3_ok, ev_termZ B9 Mw9c_represents piv4_ok, ev_termZ B9 Mw9c_represents piv5_ok, ev_termZ B9 Mw9c_represents piv6_ok, ev_termZ B9 Mw9c_represents piv7_ok, ev_termZ B9 Mw9c_represents piv8_ok, ev_termZ B9 Mw9c_represents piv9_ok, ev_termZ B9 Mw9c_represents piv10_ok, ev_termZ B9 Mw9c_represents piv11_ok, ev_termZ B9 Mw9c_represents piv12_ok, ev_termZ B9 Mw9c_represents piv13_ok, ev_termZ B9 Mw9c_represents piv14_ok, ev_termZ B9 Mw9c_represents piv15_ok, ev_termZ B9 Mw9c_represents piv16_ok, ev_termZ B9 Mw9c_represents piv17_ok] at hk
  have ht : t3TargetM 5 idx = scalar * ev B9 (tgtT3 5 idx) := by
    have h := t3TargetM_eq_ev 5 idx
    try simp only [Nat.reduceMod, Nat.reduceDiv, pow_zero, pow_one] at h
    unfold scalar
    linear_combination h
  rw [Finset.sum_apply, ht]
  simp only [Pi.smul_apply, smul_eq_mul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, add_zero, terms, Cs, t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, stabTerm]
  linear_combination (scalar / 3) * hk

end T3M5

/-- **χ(|T3⟩^⊗5) ≤ 18 against `IsStabP 3`.** -/
theorem t3_m5_stabRankP_le_eighteen : stabRankP 3 (t3TargetM 5) ≤ 18 :=
  stabRankP_le_of_terms 3 T3M5.terms _ T3M5.terms_isStab T3M5.target_eq

/-- The same bound against the qutrit predicate `IsStab`. -/
theorem t3_m5_stabRank_le_eighteen : Stabilizer.stabRank (IsStab (n := 5)) (t3TargetM 5) ≤ 18 := by
  rw [stabRank_eq_stabRankP]
  exact t3_m5_stabRankP_le_eighteen

end StabRank
