/-
Slice 1 of 9 of the kernel check of `T3M5StabRank`: the identity at
the indices `q * 27 + i`. Generated by
`lean_proofs/tools/gen_witness_lean.py`; do not edit by hand.
-/
import LeanProofs.T3M5Data

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace T3M5

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem key1 : ∀ i : Fin 27, Den • tgtT3 5 (cidx ⟨1, by norm_num⟩ i) = rhsZ (digitsP 3 5 (cidx ⟨1, by norm_num⟩ i)) := by
  decide +kernel

end T3M5

end StabRank
