/-
`χ(|T3⟩^⊗5) ≤ 18` against `stabRankP 3`, from the witness of
`bounds/T3-m5-upper-18.json`.

Generated by `lean_proofs/tools/gen_witness_lean.py`; do not edit by hand. The
terms are the file's, entered as `stabTerm 3 5 k x0 W Q l` with the pivot
columns of `W` (`Q` is read as an upper-triangular form, as the verifier reads
it). Each coefficient is the integer vector `Cj` in the basis `B9` of
`LeanProofs/ReflectQutrit.lean`: the file's coefficient, divided by the
`√3^k` normalisation of its term and by the common scalar in front of the
target (`t3TargetM_eq_ev`), times `Den = 3`. The pointwise identity is
decided by the kernel on integer vectors at all 243 digit strings (`key`) and
carried to `ℂ` by `ev_termZ`.
-/
import LeanProofs.ReflectQutrit

set_option linter.style.longLine false

namespace StabRank

open Stabilizer

namespace T3M5

/-- The scalar in front of the target in `T3` at `m = 5`. -/
noncomputable def scalar : ℂ := ((1 / Real.sqrt 3 : ℝ) : ℂ) ^ 5

def x0_0 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 0]
def W0 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q0 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 2, 2, 2], ![0, 1, 2, 2], ![0, 0, 1, 2], ![0, 0, 0, 0]]
def l0 : Fin 4 → ZMod (stabPeriod 3) := ![0, 0, 0, 1]
def piv0 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv0_ok : ∀ j j', W0 j (piv0 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t0 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_0 W0 Q0 l0
theorem t0_isStab : IsStabP 3 t0 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv0 piv0_ok)
def C0 : Fin 12 → ℤ := ![1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0]

def x0_1 : Fin 5 → ZMod 3 := ![0, 0, 0, 2, 1]
def W1 : Fin 3 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2]]
def Q1 : Fin 3 → Fin 3 → ZMod 3 := ![![2, 0, 0], ![0, 2, 0], ![0, 0, 2]]
def l1 : Fin 3 → ZMod (stabPeriod 3) := ![1, 1, 1]
def piv1 : Fin 3 → Fin 5 := ![0, 1, 2]
theorem piv1_ok : ∀ j j', W1 j (piv1 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t1 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 3 x0_1 W1 Q1 l1
theorem t1_isStab : IsStabP 3 t1 :=
  isStabP_stabTerm 3 5 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv1 piv1_ok)
def C1 : Fin 12 → ℤ := ![0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0]

def x0_2 : Fin 5 → ZMod 3 := ![0, 0, 0, 2, 1]
def W2 : Fin 3 → Fin 5 → ZMod 3 := ![![1, 0, 0, 1, 1], ![0, 1, 0, 1, 1], ![0, 0, 1, 0, 2]]
def Q2 : Fin 3 → Fin 3 → ZMod 3 := ![![2, 1, 0], ![0, 2, 0], ![0, 0, 2]]
def l2 : Fin 3 → ZMod (stabPeriod 3) := ![1, 1, 1]
def piv2 : Fin 3 → Fin 5 := ![0, 1, 2]
theorem piv2_ok : ∀ j j', W2 j (piv2 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t2 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 3 x0_2 W2 Q2 l2
theorem t2_isStab : IsStabP 3 t2 :=
  isStabP_stabTerm 3 5 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv2 piv2_ok)
def C2 : Fin 12 → ℤ := ![3, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0]

def x0_3 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 0]
def W3 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q3 : Fin 4 → Fin 4 → ZMod 3 := ![![0, 1, 1, 1], ![0, 0, 1, 1], ![0, 0, 0, 1], ![0, 0, 0, 2]]
def l3 : Fin 4 → ZMod (stabPeriod 3) := ![2, 2, 2, 2]
def piv3 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv3_ok : ∀ j j', W3 j (piv3 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t3 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_3 W3 Q3 l3
theorem t3_isStab : IsStabP 3 t3 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv3 piv3_ok)
def C3 : Fin 12 → ℤ := ![(-1), 0, 0, (-2), 0, 0, 0, 0, 0, 0, 0, 0]

def x0_4 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 0]
def W4 : Fin 3 → Fin 5 → ZMod 3 := ![![1, 1, 0, 0, 1], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q4 : Fin 3 → Fin 3 → ZMod 3 := ![![0, 0, 1], ![0, 2, 0], ![0, 0, 0]]
def l4 : Fin 3 → ZMod (stabPeriod 3) := ![1, 1, 1]
def piv4 : Fin 3 → Fin 5 := ![0, 2, 3]
theorem piv4_ok : ∀ j j', W4 j (piv4 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t4 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 3 x0_4 W4 Q4 l4
theorem t4_isStab : IsStabP 3 t4 :=
  isStabP_stabTerm 3 5 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv4 piv4_ok)
def C4 : Fin 12 → ℤ := ![3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

def x0_5 : Fin 5 → ZMod 3 := ![0, 0, 0, 2, 1]
def W5 : Fin 3 → Fin 5 → ZMod 3 := ![![1, 0, 0, 2, 0], ![0, 1, 0, 2, 0], ![0, 0, 1, 1, 1]]
def Q5 : Fin 3 → Fin 3 → ZMod 3 := ![![0, 2, 1], ![0, 0, 1], ![0, 0, 0]]
def l5 : Fin 3 → ZMod (stabPeriod 3) := ![0, 0, 0]
def piv5 : Fin 3 → Fin 5 := ![0, 1, 2]
theorem piv5_ok : ∀ j j', W5 j (piv5 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t5 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 3 x0_5 W5 Q5 l5
theorem t5_isStab : IsStabP 3 t5 :=
  isStabP_stabTerm 3 5 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv5 piv5_ok)
def C5 : Fin 12 → ℤ := ![0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0]

def x0_6 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 1]
def W6 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q6 : Fin 4 → Fin 4 → ZMod 3 := ![![2, 0, 0, 0], ![0, 1, 2, 1], ![0, 0, 1, 1], ![0, 0, 0, 2]]
def l6 : Fin 4 → ZMod (stabPeriod 3) := ![1, 1, 1, 2]
def piv6 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv6_ok : ∀ j j', W6 j (piv6 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t6 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_6 W6 Q6 l6
theorem t6_isStab : IsStabP 3 t6 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv6 piv6_ok)
def C6 : Fin 12 → ℤ := ![0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0]

def x0_7 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 1]
def W7 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q7 : Fin 4 → Fin 4 → ZMod 3 := ![![0, 1, 1, 1], ![0, 0, 1, 1], ![0, 0, 0, 1], ![0, 0, 0, 1]]
def l7 : Fin 4 → ZMod (stabPeriod 3) := ![1, 1, 1, 2]
def piv7 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv7_ok : ∀ j j', W7 j (piv7 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t7 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_7 W7 Q7 l7
theorem t7_isStab : IsStabP 3 t7 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv7 piv7_ok)
def C7 : Fin 12 → ℤ := ![0, (-2), 0, 0, (-1), 0, 0, 0, 0, 0, 0, 0]

def x0_8 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 1]
def W8 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q8 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 2, 2, 2], ![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]]
def l8 : Fin 4 → ZMod (stabPeriod 3) := ![1, 2, 2, 2]
def piv8 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv8_ok : ∀ j j', W8 j (piv8 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t8 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_8 W8 Q8 l8
theorem t8_isStab : IsStabP 3 t8 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv8 piv8_ok)
def C8 : Fin 12 → ℤ := ![0, (-1), 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

def x0_9 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 1]
def W9 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q9 : Fin 4 → Fin 4 → ZMod 3 := ![![0, 1, 1, 1], ![0, 0, 0, 1], ![0, 0, 0, 1], ![0, 0, 0, 0]]
def l9 : Fin 4 → ZMod (stabPeriod 3) := ![1, 2, 2, 1]
def piv9 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv9_ok : ∀ j j', W9 j (piv9 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t9 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_9 W9 Q9 l9
theorem t9_isStab : IsStabP 3 t9 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv9 piv9_ok)
def C9 : Fin 12 → ℤ := ![0, 1, 0, 0, (-1), 0, 0, 0, 0, 0, 0, 0]

def x0_10 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 1]
def W10 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q10 : Fin 4 → Fin 4 → ZMod 3 := ![![2, 0, 0, 0], ![0, 0, 1, 0], ![0, 0, 0, 0], ![0, 0, 0, 0]]
def l10 : Fin 4 → ZMod (stabPeriod 3) := ![1, 1, 1, 0]
def piv10 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv10_ok : ∀ j j', W10 j (piv10 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t10 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_10 W10 Q10 l10
theorem t10_isStab : IsStabP 3 t10 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv10 piv10_ok)
def C10 : Fin 12 → ℤ := ![0, 1, 0, 0, (-1), 0, 0, 0, 0, 0, 0, 0]

def x0_11 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 1]
def W11 : Fin 3 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 1, 0, 1], ![0, 0, 0, 1, 2]]
def Q11 : Fin 3 → Fin 3 → ZMod 3 := ![![1, 1, 2], ![0, 1, 1], ![0, 0, 2]]
def l11 : Fin 3 → ZMod (stabPeriod 3) := ![1, 0, 1]
def piv11 : Fin 3 → Fin 5 := ![0, 1, 3]
theorem piv11_ok : ∀ j j', W11 j (piv11 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t11 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 3 x0_11 W11 Q11 l11
theorem t11_isStab : IsStabP 3 t11 :=
  isStabP_stabTerm 3 5 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv11 piv11_ok)
def C11 : Fin 12 → ℤ := ![0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

def x0_12 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 2]
def W12 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q12 : Fin 4 → Fin 4 → ZMod 3 := ![![2, 2, 2, 2], ![0, 2, 2, 2], ![0, 0, 2, 2], ![0, 0, 0, 2]]
def l12 : Fin 4 → ZMod (stabPeriod 3) := ![2, 2, 2, 2]
def piv12 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv12_ok : ∀ j j', W12 j (piv12 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t12 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_12 W12 Q12 l12
theorem t12_isStab : IsStabP 3 t12 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv12 piv12_ok)
def C12 : Fin 12 → ℤ := ![0, 0, (-2), 0, 0, (-1), 0, 0, 0, 0, 0, 0]

def x0_13 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 2]
def W13 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q13 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 1, 1, 1], ![0, 1, 1, 1], ![0, 0, 1, 1], ![0, 0, 0, 1]]
def l13 : Fin 4 → ZMod (stabPeriod 3) := ![1, 1, 1, 1]
def piv13 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv13_ok : ∀ j j', W13 j (piv13 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t13 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_13 W13 Q13 l13
theorem t13_isStab : IsStabP 3 t13 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv13 piv13_ok)
def C13 : Fin 12 → ℤ := ![0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0]

def x0_14 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 2]
def W14 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q14 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 0, 0, 1], ![0, 0, 0, 0], ![0, 0, 0, 0], ![0, 0, 0, 1]]
def l14 : Fin 4 → ZMod (stabPeriod 3) := ![2, 0, 0, 2]
def piv14 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv14_ok : ∀ j j', W14 j (piv14 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t14 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_14 W14 Q14 l14
theorem t14_isStab : IsStabP 3 t14 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv14 piv14_ok)
def C14 : Fin 12 → ℤ := ![0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0]

def x0_15 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 2]
def W15 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q15 : Fin 4 → Fin 4 → ZMod 3 := ![![2, 2, 0, 1], ![0, 1, 0, 2], ![0, 0, 0, 0], ![0, 0, 0, 2]]
def l15 : Fin 4 → ZMod (stabPeriod 3) := ![2, 2, 0, 2]
def piv15 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv15_ok : ∀ j j', W15 j (piv15 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t15 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_15 W15 Q15 l15
theorem t15_isStab : IsStabP 3 t15 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv15 piv15_ok)
def C15 : Fin 12 → ℤ := ![0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0]

def x0_16 : Fin 5 → ZMod 3 := ![0, 0, 0, 0, 2]
def W16 : Fin 4 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 1, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q16 : Fin 4 → Fin 4 → ZMod 3 := ![![1, 2, 1, 2], ![0, 1, 1, 2], ![0, 0, 1, 1], ![0, 0, 0, 1]]
def l16 : Fin 4 → ZMod (stabPeriod 3) := ![0, 0, 1, 0]
def piv16 : Fin 4 → Fin 5 := ![0, 1, 2, 3]
theorem piv16_ok : ∀ j j', W16 j (piv16 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t16 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 4 x0_16 W16 Q16 l16
theorem t16_isStab : IsStabP 3 t16 :=
  isStabP_stabTerm 3 5 4 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv16 piv16_ok)
def C16 : Fin 12 → ℤ := ![0, 0, (-1), 0, 0, (-2), 0, 0, 0, 0, 0, 0]

def x0_17 : Fin 5 → ZMod 3 := ![0, 1, 0, 0, 1]
def W17 : Fin 3 → Fin 5 → ZMod 3 := ![![1, 0, 0, 0, 2], ![0, 0, 1, 0, 2], ![0, 0, 0, 1, 2]]
def Q17 : Fin 3 → Fin 3 → ZMod 3 := ![![1, 0, 2], ![0, 0, 0], ![0, 0, 1]]
def l17 : Fin 3 → ZMod (stabPeriod 3) := ![2, 0, 2]
def piv17 : Fin 3 → Fin 5 := ![0, 2, 3]
theorem piv17_ok : ∀ j j', W17 j (piv17 j') = if j = j' then 1 else 0 := by
  decide +kernel
noncomputable def t17 : Fin (3 ^ 5) → ℂ := stabTerm 3 5 3 x0_17 W17 Q17 l17
theorem t17_isStab : IsStabP 3 t17 :=
  isStabP_stabTerm 3 5 3 _ _ _ _ (affinePtP_injective_of_pivots _ _ piv17 piv17_ok)
def C17 : Fin 12 → ℤ := ![0, 0, (-3), 0, 0, 0, 0, 0, 0, 0, 0, 0]

def Den : ℤ := 3

/-- The integer side of `Σ_j C_j · σ_j` at a digit string. -/
def rhsZ (x : Fin 5 → ZMod 3) : Fin 12 → ℤ :=
  termZ Mw9c C0 x0_0 W0 Q0 l0 piv0 x
    + termZ Mw9c C1 x0_1 W1 Q1 l1 piv1 x
    + termZ Mw9c C2 x0_2 W2 Q2 l2 piv2 x
    + termZ Mw9c C3 x0_3 W3 Q3 l3 piv3 x
    + termZ Mw9c C4 x0_4 W4 Q4 l4 piv4 x
    + termZ Mw9c C5 x0_5 W5 Q5 l5 piv5 x
    + termZ Mw9c C6 x0_6 W6 Q6 l6 piv6 x
    + termZ Mw9c C7 x0_7 W7 Q7 l7 piv7 x
    + termZ Mw9c C8 x0_8 W8 Q8 l8 piv8 x
    + termZ Mw9c C9 x0_9 W9 Q9 l9 piv9 x
    + termZ Mw9c C10 x0_10 W10 Q10 l10 piv10 x
    + termZ Mw9c C11 x0_11 W11 Q11 l11 piv11 x
    + termZ Mw9c C12 x0_12 W12 Q12 l12 piv12 x
    + termZ Mw9c C13 x0_13 W13 Q13 l13 piv13 x
    + termZ Mw9c C14 x0_14 W14 Q14 l14 piv14 x
    + termZ Mw9c C15 x0_15 W15 Q15 l15 piv15 x
    + termZ Mw9c C16 x0_16 W16 Q16 l16 piv16 x
    + termZ Mw9c C17 x0_17 W17 Q17 l17 piv17 x

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- The identity on integer vectors, decided by the kernel at every index. -/
theorem key : ∀ idx : Fin (3 ^ 5), Den • tgtT3 5 idx = rhsZ (digitsP 3 5 idx) := by
  decide +kernel

noncomputable def terms : Fin 18 → (Fin (3 ^ 5) → ℂ) :=
  ![t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17]
def Cs : Fin 18 → Fin 12 → ℤ := ![C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16, C17]

theorem terms_isStab : ∀ j, IsStabP 3 (terms j) := by
  intro j
  fin_cases j
  exacts [t0_isStab, t1_isStab, t2_isStab, t3_isStab, t4_isStab, t5_isStab, t6_isStab, t7_isStab, t8_isStab, t9_isStab, t10_isStab, t11_isStab, t12_isStab, t13_isStab, t14_isStab, t15_isStab, t16_isStab, t17_isStab]

set_option linter.unusedSimpArgs false in
theorem target_eq : t3TargetM 5 = ∑ j, (scalar / 3 * ev B9 (Cs j)) • terms j := by
  funext idx
  have hk := congrArg (ev B9) (key idx)
  rw [ev_zsmul] at hk
  simp only [rhsZ, ev_add, Den, Int.cast_one, Int.cast_ofNat, one_mul, ev_termZ B9 Mw9c_represents piv0_ok, ev_termZ B9 Mw9c_represents piv1_ok, ev_termZ B9 Mw9c_represents piv2_ok, ev_termZ B9 Mw9c_represents piv3_ok, ev_termZ B9 Mw9c_represents piv4_ok, ev_termZ B9 Mw9c_represents piv5_ok, ev_termZ B9 Mw9c_represents piv6_ok, ev_termZ B9 Mw9c_represents piv7_ok, ev_termZ B9 Mw9c_represents piv8_ok, ev_termZ B9 Mw9c_represents piv9_ok, ev_termZ B9 Mw9c_represents piv10_ok, ev_termZ B9 Mw9c_represents piv11_ok, ev_termZ B9 Mw9c_represents piv12_ok, ev_termZ B9 Mw9c_represents piv13_ok, ev_termZ B9 Mw9c_represents piv14_ok, ev_termZ B9 Mw9c_represents piv15_ok, ev_termZ B9 Mw9c_represents piv16_ok, ev_termZ B9 Mw9c_represents piv17_ok] at hk
  have ht : t3TargetM 5 idx = scalar * ev B9 (tgtT3 5 idx) := by
    have h := t3TargetM_eq_ev 5 idx
    try simp only [Nat.reduceMod, Nat.reduceDiv, pow_zero, pow_one] at h
    unfold scalar
    linear_combination h
  rw [Finset.sum_apply, ht]
  simp only [Pi.smul_apply, smul_eq_mul, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero,
    Matrix.cons_val_succ, add_zero, terms, Cs, t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, stabTerm]
  linear_combination (scalar / 3) * hk

end T3M5

/-- **χ(|T3⟩^⊗5) ≤ 18 against `IsStabP 3`.** -/
theorem t3_m5_stabRankP_le_eighteen : stabRankP 3 (t3TargetM 5) ≤ 18 :=
  stabRankP_le_of_terms 3 T3M5.terms _ T3M5.terms_isStab T3M5.target_eq

/-- The same bound against the qutrit predicate `IsStab`. -/
theorem t3_m5_stabRank_le_eighteen : Stabilizer.stabRank (IsStab (n := 5)) (t3TargetM 5) ≤ 18 := by
  rw [stabRank_eq_stabRankP]
  exact t3_m5_stabRankP_le_eighteen

end StabRank
